### ISSUE TITLE
Unable to report type mismatch for unordered vec

### ISSUE THREAD

**Issue by rachel960122** [ucsd-progsys/liquidhaskell#1175]
The following module was accepted:

```
module BadVec where

data OVec a = ONil
            | (:>>) {oHd :: a, oTl :: OVec a}
infixr 5 :>>

{-@ data OVec a = ONil
               | (:>>) {oHd :: a,
                        oTl :: OVec {v:a | v >= oHd}} @-}


{-@ data OVec [mylen] @-}
{-@ measure mylen @-}
{-@ mylen :: OVec a -> Nat @-}
mylen :: OVec a -> Int
mylen ONil       = 0
mylen (_ :>> xs) = 1 + mylen xs

{-@ badVec :: OVec Int @-}
badVec :: OVec Int
badVec = 1 :>> 3 :>> 2 :>> ONil
```

I think the last line should be rejected given the definition of `OVec`. Also, if we delete the definition for `mylen`, the last line will be rejected correctly.

**Comment by ranjitjhala** [comment]
Aha, thanks for pointing this out! The issue is that you have 
_two separate_ `data` refinements for `OVec`:

1. The `data OVec a = ONil ...` which defines the *ordering* invariant,
2. The `data OVec [mylen]` which defines the *default metric* for the type.

However, LH seems to just _ignore_ the first one and so happily checks `badVec`.

You can fix this by _merging_ the two `data` definitions as:

```haskell
{-@ data OVec [mylen] a = ONil
               | (:>>) {oHd :: a,
                        oTl :: OVec {v:a | v >= oHd}} @-}
```

And then `badVec` is indeed rejected, as shown here:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1511994723_10782.hs

Many thanks for pointing this out! We should report a proper _error message_ when there 
are multiple `data` definitions.

**Comment by rachel960122** [comment]
Thank you so much for the explanation! It makes a lot more sense now.

**Comment by ranjitjhala** [comment]
We now produce an error message like:

```
 /Users/rjhala/research/stack/liquidhaskell/tests/errors/DupData.hs:14:10: Error: Multiple specifications for `OVec` :

 14 | {-@ data OVec [mylen] @-}
               ^

     Conflicting definitions at

     * /Users/rjhala/research/stack/liquidhaskell/tests/errors/DupData.hs:14:10

     * /Users/rjhala/research/stack/liquidhaskell/tests/errors/DupData.hs:9:10
```

**Comment by rachel960122** [comment]
Thanks for improving the error message! It's much clearer now :)
