### ISSUE TITLE
Using a rank2 type as refinement

### ISSUE THREAD

**Issue by vikraman** [ucsd-progsys/liquidhaskell#1176]
If `p :: a -> Bool` is a predicate on `a`, is it possible to write this refinement type `{ forall a. p a }`?

@atondwal tells me this was possible before, but it doesn't parse anymore on develop. I needed something like this to write some proofs using LEM for classical first order logic.

**Comment by ranjitjhala** [comment]
Not sure exactly what you are looking for ... did you mean something like
this?

https://ucsd-progsys.github.io/liquidhaskell-blog/2013/06/03/abstracting-over-refinements.lhs/

**Comment by nikivazou** [comment]
@vikraman, we do not allow `forall` inside the refinements, but you can use our paper HOL -> Refinement types encoding to encode foralls as dependent function types. Is there a reason you do not want to use this encoding?

**Comment by atondwal** [comment]
Err, sorry, vikraman, I think I forgot to mention, the syntax is a little different. You can reflect foralls into the logic as lamdbas, as follows:

```
{-@ LIQUID "--higherorder" @-}

{-@ measure prop :: a -> Bool @-}

{-@ reflectAll :: p:(a->Bool) -> { prop (\x:a -> (p x)) } @-}
reflectAll :: (a -> Bool) -> ()
reflectAll p = () 
```

However, the problem is that I can't figure out how to convince LH of such a `reflectAll` without axiomatizing it with GADTs.

@nikivazou the reason we might not want to use that embedding is to make use of 1) LEM and 2) congruence closure, both of which we get if we just reflect the quantified term into SMT as an uninterpreted symbol, especially if we write the adjoint `reifyAll`

**Comment by ranjitjhala** [comment]
Nope, no `forall` in refinements. never!  :)

You can use the HOL encoding? or some other machinery?

**Comment by atondwal** [comment]
The bigger problem is we should actually have a function on Props without
specifying the numbers of quantifiers (ie have some way treat `a -> Bool`
the same as Bool --- otherwise our HOL encoding is broken!)  If we don't do
it by refining lambdas,  I suppose there might be some work around with
typeclasses?

On Dec 5, 2017 15:38, "Ranjit Jhala" <notifications@github.com> wrote:

Closed #1176 <https://github.com/ucsd-progsys/liquidhaskell/issues/1176>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ucsd-progsys/liquidhaskell/issues/1176#event-1373776769>,
or mute the thread

**Comment by ranjitjhala** [comment]
Don't follow what

> otherwise our HOL encoding is broken

means. What's a concrete test that should pass/fail?

​

**Comment by atondwal** [comment]
Say we want to write the LEM, `forall a :Prop . a \/ not a`. We can write this for `Bool`s (i.e. quantifier-free propositions) in LH as `lemBool :: a:Bool -> a \/ not a`, but we can't quantify over all Props. We'd want to use a postulate something like `lem :: a : b -> a \/ not a`, but this is ill-sorted; we don't know what it means to take the negation or disjunction of `b`s if `b := a -> Bool`, or if  `b := (a,Bool)`, or for that matter a `(a,b->(c,Bool))` or any such encoding of quantifiers in PaT.
