### ISSUE TITLE
Failed to verify when a type parameter is instantiated

### ISSUE THREAD

**Issue by autotaker** [ucsd-progsys/liquidhaskell#1219]
I tried the ["Ordered Lists" Demo](http://goto.ucsd.edu:8090/index.html#?demo=Order.hs).
LiquidHaskell verified the `insert` has the refinement type `Ord a => a -> IncList a -> IncList a`,
but it FAILED to verify the property when I changed type parameter `a` to `Int`.

Here is the program I tested.
```haskell
module PuttingThingsInOrder  where

{-@ LIQUID "--notermination" @-}
{-@ type IncrIntList = IncrList Int @-}
{-@ type IncrList a = [a]<{\xi xj -> xi <= xj}> @-}

{-@ insert :: Ord a => a -> IncrList a -> IncrList a @-}
insert :: Ord a => a -> [a] -> [a]
insert y []     = [y]
insert y (x:xs)
  | y <= x      = y : x : xs
  | otherwise   = x : insert y xs

{-@ insert' :: Int -> IncrList Int -> IncrList Int @-}
insert' :: Int -> [Int] -> [Int]
insert' y []     = [y]
insert' y (x:xs)
  | y <= x      = y : x : xs
  | otherwise   = x : insert' y xs
```

Error message is (At Line 16):
```
Error: Liquid Type Mismatch
  Inferred type
    VV : Int
 
  not a subtype of Required type
    VV : {VV : Int | ?a <= VV}
 
  In Context
    ?a : Int
```
What is the reason of this strange behaviour?

**Comment by ranjitjhala** [comment]
This is actually a feature and not a bug :)

The property is in fact not true when you monomorphize the type
specification but is true with the polymorphic signature, due to
parametricity :)

I think I have an explanation written up that I will dig up and post in
this issue.

**Comment by ranjitjhala** [comment]
LH is a _modular_ checker. That is, the type of a term `f x` is obtained from the *specification* i.e. _output type_ of `f` not by actually looking at the *implementation*. Thus, to LH the code:

```haskell
{-@ insert' :: Int -> IncrList Int -> IncrList Int @-}
insert' :: Int -> [Int] -> [Int]
insert' y []     = [y]
insert' y (x:xs)
  | y <= x      = y : x : xs
  | otherwise   = x : insert' y xs
```

is actually equivalent to:

```haskell
{-@ insertRECURSIVE :: Int -> IncrList Int -> IncrList Int @-}
insertRECURSIVE = undefined -- the implementation is ignored... 

{-@ insert' :: Int -> IncrList Int -> IncrList Int @-}
insert' :: Int -> [Int] -> [Int]
insert' y []     = [y]
insert' y (x:xs)
  | y <= x      = y : x : xs
  | otherwise   = x : insertRECURSIVE y xs
```

Now, the problem is this: the type of `insertRECURSIVE` is such that the output is just an `IncrList Int`, that is, LH *doesn't know* if the elements in the output are actually all greater than `x`! 

Thus, LH rejects `x : insertRECURSIVE y xs` as that new list may perhaps NOT be sorted (it could be, e.g. that the implementation of `insertRECURSIVE` just returned the list `[0]` which is an `IncrList Int` but if `x` was `10` then `x : [0]` would not be an `IncrList Int`.


Now, lets see what happens when the types are polymorphic:

```haskell
{-@ insertPOLY :: a -> IncrList a -> IncrList a @-}
insertPOLY = undefined -- the implementation is ignored... 

{-@ insert' :: a -> IncrList a -> IncrList a @-}
insert' :: Int -> [Int] -> [Int]
insert' y []     = [y]
insert' y (x:xs)
  | y <= x      = y : x : xs
  | otherwise   = x : insertPOLY y xs
```

now, `insertPOLY y xs` returns an `IncrList a` where `y :: a` and `xs :: IncrList a`

Now, at the call-site, LH *infers* that `a` is  `{v:Int | x <= v}` , as  both:

- ` x <= y` because of the guard,
- `xs :: IncrList {v:a | x <= v}` because `x : xs` was an `IncrList`

and so the output of `insertPOLY y xs` is `IncrList {v:a | x <= v}` and so 
`x : insertPOLY y xs` is indeed an `IncrList a` (as all the elements in the 
tail are larger than the head `x`.

Does that help?

**Comment by autotaker** [comment]
Thank you for quick and detailed explanation!
Then, are there any refinement type syntax to denote that a monomorphic function is polymorphic to refinement types?
(e.g. I'd like to write `insert :: forall (a <: Int). a -> IncList a -> IncList a` or something like that.)

**Comment by autotaker** [comment]
I just find by myself that the spec `insert :: forall <p :: Int -> Bool> . Int<p> -> IncrList (Int<p>) -> IncrList (Int<p>)` is what I wanted. Thank you!

**Comment by ranjitjhala** [comment]
Awesome! Was about send that to you when I got back to my laptop, I am
delighted that you found it out by yourself :-)
