### ISSUE TITLE
Common command-line flags should be better documented

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1262]
The documentation for most command line flags is (as far as I can find) just the description in `liquid --help`. So far I've had to use the following flags to do simple proofs:

- `--higherorder`
- `--prune-unsorted`
- `--exact-data-cons`
- `--automatic-instances=liquidinstances`
- `--ple`

For most of these I've gotten some intuition about when to use them, but it would be nice to have for each (and any other common flags people might run into):

- what the flag does, in simple terms;
- when you might need to use the flag, preferably with an actual runnable code example; and
- why this flag is not enabled by default (e.g. it makes things undecidable/introduces potential unsoundness/makes error messages worse).

I'm happy to help write this documentation, but someone would have to explain to me what the flags do exactly.

**Comment by nikivazou** [comment]
- `prune-unsorted` allows you to define measures of ADTs that are of some specific type. Eg, you can always define a measure on lists `[a]` but to define a measure on, eg `[Tree a]` you need to use prune unsorted. 

- `ple` is the Proof by Logic Evaluation that automatically does unfodlings for you when proving. I though it is the same as `automatic-instances=liquidinstances`.

- `exact-dc` allows you to reflect the data types and functions on them and `higherorder` allows you to reflect higher order functions. Maybe these two should be merged in one flag "alias" since they are frequently used in theorem proving mode.  

I too believe it would be better if you edit the documentation, since you see these flags as a user (unlike me that I see them as a developer :) )

**Comment by ranjitjhala** [comment]
Niki, at the least can you add the below (above) descriptions to the
README? @wkunkel can then edit it or add questions about what remains
unclear?

More generally the readme is getting long so maybe we should look into
migrating it to some proper documentation system eg the one stack uses?

**Comment by ranjitjhala** [comment]
Hi @wkunkel see above PR. The only missing thing is `--prune-unsorted` which, while inscrutable, is described in the [README](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/README.md#prune-unsorted-predicates) 😃

**Comment by nikivazou** [comment]
I cannot do it soon (another interview in EU on Monday). 

Let's sync to create proper documentation when I am back.

**Comment by ranjitjhala** [comment]
:thumbs up:👍

**Comment by ranjitjhala** [comment]
For the record, this is the thing:

http://www.mkdocs.org/#getting-started
