### ISSUE TITLE
My isJust is inferior to your isJust

### ISSUE THREAD

**Issue by goldfirere** [ucsd-progsys/liquidhaskell#1264]
This works quite nicely:

```
{-@ fromJust :: { m:Maybe a | isJust m } -> a @-}
fromJust :: Maybe a -> a
fromJust (Just x) = x
fromJust Nothing  = error "Nothing"
```

Liquid Haskell correctly figures out that my `error` case is impossible. But when I try to conjure up my own brand of this magic, I fail:

```
{-@ LIQUID "--exactdc" @-}

module Maybe where

data Maybe2 a = Nothing2 | Just2 a

{-@ reflect isJust2 @-}
isJust2 :: Maybe2 a -> Bool
isJust2 (Just2 _) = True
isJust2 Nothing2  = False

{-@ fromJust :: { m:Maybe2 a | isJust2 m } -> a @-}
fromJust :: Maybe2 a -> a
fromJust (Just2 x) = x
fromJust Nothing2  = error "Nothing"
```

The error message does not mention `isJust2` at all, making it look like LH is ignoring my type annotation. Indeed, I get the same error with the liquid type ascription as without.

Two questions:
1. What does `--exactdc` do? I was advised by @rachel960122 to use this incantation to allow me to reflect `isJust2`. It works nicely, but I'm curious as to what it does.

2. Am I doing something wrong here? How can I define a predicate like `isJust` to work over my own datatype? (My real use case is not for `Maybe`.)

**Comment by ranjitjhala** [comment]
Hi Richard,

If you change your “reflect isJust2” to “measure isJust2” your example
should work. Will say more once I get to my computer!

**Comment by ranjitjhala** [comment]
Hi @goldfirere -- see this for example:

  http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1522186129_23872.hs

(Aside @nikivazou we need to write up some documentation about `reflect` vs `measure` vs `inline`)

Due to various historical reasons, there are *two* ways of "lifting" Haskell functions into refinements: `measure` and `reflect`.

## Measures 

Have been around since day 1, see 
[this for an example](https://liquid.kosmikus.org/02-lists.html#/measures) 
and they are useful when you have 

1. functions of type: `foo :: S -> T` where additionally,
2. `S` is an ADT, and
3. `foo` has a *single* equation per data constructor.

so this is ideal for things like `len` of a list or `isJust`.
The convenient thing about measures is that we can 
use them to directly strengthen the data-constructors
(as described at the link above) and to put the relevant 
information into the typing context during pattern matching.
Basically, `measure`s let you encode "type-indexes" (e.g. `Vec a n`)
without having to hardwire a particular property (e.g. size) into the index.

## Reflects 

However, `measures` have all the above syntactic restrictions. 
The recent [refinement reflection work](https://nikivazou.github.io/static/popl18/refinement-reflection.pdf) lets us hoist arbitrary (terminating!) 
haskell functions into the refinement (not just unary functions etc.)

However, this generality comes at a price: these reflected functions 
are not associated directly with the datatype (in general, you can't 
as there maybe multiple parameters etc.) and so the user has to "control"
the unfolding as described in the paper above. 

Fortunately, "reflection" comes with a form of "type-level evaluation" 
that we call "logical evaluation". You can switch this on with 

```haskell
{-@ LIQUID "--ple" @-}
```
and when you do so, your original code works even with `reflect isJust2`

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1522186826_23876.hs

## Whats up with `--exactdc` 

The way `reflect isJust2` works is to encode the definition of  `isJust2` as a term in the 
refinement logic. As an example, suppose you instead wrote:

```haskell
{-@ reflect justNat @-}
justNat :: Maybe2 a -> Int
justNat (Just2 n) = 1
justNat (Nothing) = 0
```

Then, `reflect` would generate the following "logical definition" for `justNat`:

```
justNat z = if is$Just2 z then 1 else 0
```

Here, `is$Just2` is the "test-that-the-constructor-is-a-Just2" function, and these are 
automatically generated by `--exactdc`. The flag similarly generates "field-selectors" 
for example, 

```
{-@ reflect append @-}
append Nil ys = ys
append (Cons x xs) ys = Cons x (append xs ys)
```

gets reflected to

```
append xs ys = if is$Nil xs then ys else Cons (select_cons_1 xs) (append (select_cons_2 xs) ys)
```

where `select_cons_1` and `select_cons_2` project out the 1st and 2nd elements of the Cons constructor (i.e. head and tail). Anways, `--exactdc` simply generates these tests and selectors,
which are needed to `reflect` functions over ADTs. That flag should really be turned on by default
to minimize confusion!

In fact @nikivazou is there a reason that we don't make `--exactdc` on by default? 
[I can't think of any situation where we wouldn't want it?]

**Comment by nikivazou** [comment]
We do not have `--exactdc` on by default because it defines these selectors that are not used in "non theorem proving" mode.

**Comment by ranjitjhala** [comment]
Still the benchmarks should work regardless (or whether or not those
selectors are defined) right?

**Comment by goldfirere** [comment]
This all works and makes sense. It sounds like there's an open question about defaulting `--exactdc`, but my concerns are handled and I'd be happy to close the ticket. Thanks!

**Comment by ranjitjhala** [comment]
Thanks Richard!

On Wed, Mar 28, 2018 at 9:36 AM, Richard Eisenberg <notifications@github.com

**Comment by ranjitjhala** [comment]
Closing per above.
