### ISSUE TITLE
Does this compile with GHC 8.6?

### ISSUE THREAD

**Issue by spacekitteh** [ucsd-progsys/liquidhaskell#1415]

**Comment by ranjitjhala** [comment]
Not yet, but I think I'll try to put that next on my TODO list!

**Comment by ranjitjhala** [comment]
@nikivazou did we ever start a branch to move to GHC 8.6 I can't recall?

**Comment by nikivazou** [comment]
I didn't :(

**Comment by spacekitteh** [comment]
What would have to be done to do this? Although it might be worth going straight to 8.8, as it's due to be released in less than two weeks.

**Comment by ranjitjhala** [comment]
Yikes is 8.8 on the horizon :-)

My sense is it _shouldn't_ be too difficult; the GHC API has
likely changed a bit so various things will have to be updated
to support it.

The biggest things are:

1. Update the "Desugar" directory


https://github.com/ucsd-progsys/liquidhaskell/blob/develop/README.md#updating-ghc

   which is basically just ripped from GHC, (because we have to tweak it in
one
   little place; we really ought to just push that tweak back into GHC
because
   that would make this step trivial!)

2. Fix the type errors so stuff works with the updated GHC-API.

(Another, maybe more ambitious thought is to switch to using
 the new ghc-lib package from Neil Mitchell and co. but not
 clear if that's going to be easier?)

Classes end next week so I should have some time to do it after 3/15

**Comment by spacekitteh** [comment]
It seems that ghc-lib doesn't have a runtime, so you can't execute any code at compile time (e.g. template haskell).

I'll look into submitting it as a patch to GHC, but I doubt it'd make 8.8 in time.

**Comment by spacekitteh** [comment]
Actually, is the patch still even needed?

**Comment by ranjitjhala** [comment]
Well for ghc 843 it was needed: I recall putting it in myself to get the
right source spans for errors. However, iirc @nomeata had started the ball
rolling on basically getting that incorporated in ghc so maybe it’s merged
into ghc 864? Let me find the relevant link from slack...

**Comment by spacekitteh** [comment]
Relevant: https://gitlab.haskell.org/ghc/ghc/merge_requests/505

**Comment by ranjitjhala** [comment]
@spacekitteh I made a branch #1426 that (surprisingly!) is *mostly* 
working with ghc 8.6.3.
