### ISSUE TITLE
PLE breaks equational steps

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1420]
The following is SAFE 

```
    distributivityP :: Eq a => [a] -> [a] -> ()
    {-@ distributivityP 
      :: xs:[a] -> ys:[a] 
      -> {reverse (xs ++ ys) == reverse ys ++ reverse xs} @-}
    distributivityP xs@[] ys
      =   reverse ([] ++ ys)
      ==. reverse ys 
          ? leftIdP (reverse ys)
      ==. (reverse ys) ++ []  -- errors with ple on
      ==. reverse ys ++ reverse [] 
      *** QED 

    distributivityP (x:xs) ys
      =   undefined 
```

But if I activate ple (`{-@ ple distributivityP @-}`) I get two errors (one for the undefined and one for the equational step noted above). Check it here: http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1552380552_17443.hs

**Comment by ranjitjhala** [comment]
@nikivazou -- this is not a PLE bug, but "feature" :-) 

Specifically, if you replace the import

```haskell
import Language.Haskell.Liquid.Equational
```

with 

```haskell
import Language.Haskell.Liquid.ProofCombinators 
```

then the code is SAFE. The reason is that:

(1) I have _disabled_ polymorphic instantiation for refinements in "reflection/ple" mode, 
     which greatly speeds up verification, however,
(2) For the cases where you _do_ need it, e.g. when using the `?` combinator, you can recover 
     it by using abstract refinements (which are still instantiated and solved as before).

So the difference between the two modules is in the signature for `?` namely

```haskell
-- in L.H.L.Equational
(?) :: a -> Proof -> a
x ? _ = x
{-# INLINE (?)   #-}

-- in L.H.L.ProofCombinators
{-@ (?) :: forall a b <pa :: a -> Bool, pb :: b -> Bool>. a<pa> -> b<pb> -> a<pa> @-}
(?) :: a -> b -> a
x ? _ = x
{-# INLINE (?)   #-}
```

See for example, 

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1552492123_17788.hs

**Comment by nikivazou** [comment]
Oh! Smart :) 

I assume you can add these abstract refinements to the `==.` operator as well?
