### ISSUE TITLE
Can't inline functions from GADTs

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1424]
The following code causes a sort error:
```haskell
{-# LANGUAGE GADTs #-}
{-@ LIQUID "--exact-data-cons" @-}
module Gadt where

data Foo a where
  A :: Foo Int
  B :: Foo Bool

{-@ inline f @-}
f :: Foo a -> a -> Bool
f A x = False
f B x = x

{-@ f' :: x:Foo a -> y:a -> {v:Bool | v == f x y} @-}
f' :: Foo a -> a -> Bool
f' x y = f x y
```
The error is
```text
Error: Illegal type specification for `Gadt.f'`
  
 14 | {-@ f' :: x:Foo a -> y:a -> {v:Bool | v == f x y} @-}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
     Gadt.f' :: forall a##xo .
                (Gadt.Foo a##xo)
                -> a##xo
                   -> GHC.Types.Bool
     Sort Error in Refinement: {v : bool | v == (if is$Gadt.A x then false else (coerce a##aWG ~ bool in y))}
     Cannot unify a##aWG with a##aWO in expression: y << ceq2 >>
  because
Cannot cast y of sort a##aWO to incompatible sort a##aWG
```
This cast ought to be safe.

**Comment by ranjitjhala** [comment]
What happens if you

1 reflect f?
2 reflect f’ (and remove the signature?)

**Comment by rosekunkel** [comment]
Then it's safe. But in the context I actually want to use this, I don't think reflecting is a good solution: it seems to make LH unable to automatically verify things (and turning on PLE causes a bunch of errors).

**Comment by rosekunkel** [comment]
More context:
```haskell
{-@
data User = User
     { userId   :: Int,
       userName :: String
     , userFriend :: Int
     , userSSN    :: Int
     }
@-}
data User = User { userId::Int, userName :: String, userFriend :: Int, userSSN :: Int }
    deriving (Eq, Show)

{-@
data EntityField record typ where
   UserName :: EntityField User String
 | UserFriend :: EntityField User Int
 | UserSSN :: EntityField  User Int
@-}
data EntityField a b where
  UserName :: EntityField User String
  UserFriend :: EntityField User Int
  UserSSN :: EntityField User Int

{-@ reflect policy @-}
policy :: EntityField a b -> a -> User -> Bool
policy UserName row v = userId v == userFriend row
policy UserFriend row v = userId v == userFriend row
policy UserSSN row v = userId v == userId row

{-@ reflect project @-}
project :: EntityField a b -> a -> b
project UserName user = userName user
project UserFriend user = userFriend user
project UserSSN user = userSSN user

{-@
(==.) :: field:EntityField a b -> val:b -> RefinedFilter<{\row -> project field row == val}, {\row v -> policy field row v}> a
@-}
(==.) :: EntityField a b -> b -> RefinedFilter a
field ==. val = RefinedFilter Filter
```

I think if `policy` and `project` were inlined here, then LH would be able to check something like
`UserName ==. "alice"` against `RefinedFilter<{\row -> userName row == "alice"}, {\row v -> userId v == userFriend row}> User` automatically (but I could be mistaken).

**Comment by ranjitjhala** [comment]
Looks like the issue is that we aren't substituting 
*type variables* at places where `inline` and `reflect` 
are then "applied" within refinements. Not entirely 
surprising, since there aren't supposed to be type variables
in refinements in the first place -- these were bolted on 
later to support GADTs but I guess that needs more work! 

This would be a good thing for you to try to fix @rosekunkel 

The place to look would be where "inlined" functions are 
actually expanded at use sites, LH builds an `BareRTEnv` 
mapping names like `f` to their actual definitions 
and then uses the `BareRTEnv` to replace occurrences 
of terms within refinements like `f x y` to the actual definition 
of `f` (hence the name `inline`), using the `expand` function, 
specifically,

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Bare/Expand.hs#L703

Looks like this code ignores type parameters entirely -- you'd 
have to substitute the tyvars occurring in the definition (here `a##aWG`) 
with those actually used at the usage site (here, `a##aWO`).
This latter step is gross because you don't really have access 
to `a##aWO` -- theres no explicit type application in the 
refinements (it just says `f x y` not `f @aWO x y`).

The way to solve this would be to 

1. keep a hold of the ACTUAL "sort" of `f` in the `BareRTEnv` (may already be there)

2. computing a type-substitution corresponding to  how the type-variables 
    in the sort are "instantiated" at the usage site (i.e. by unifying against the 
    types of the arguments `x, y` -- to see how more concretely, see:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Solver/Instantiate.hs#L560-L563

3. applying the above type substitution to the "definition" of `f` (in addition to replacing the formals with the actuals as done in https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Bare/Expand.hs#L718

You can apply this substitution (`CoSub`) using 
https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Types/Visitor.hs#L346-L361

*NOTE* It occurs to me that much of this is already done inside PLE which hits this problem as it unfolds function definitions.

https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Solver/Instantiate.hs#L534-L572

I guess that code should ideally be refactored and reused to do these expansions for inlines too!

**Comment by ranjitjhala** [comment]
(Anyways, while I can do this, it may be a good exercise for you @rosekunkel 
in exploring a bit some different parts as this code should be reasonable to follow.)

**Comment by nikivazou** [comment]
Oh, this seems to be specially tricky since `Int` and `Bool` are both interpreted by SMT. 
If we are to reflect the GADT `Foo`, then what would its SMT representation look like?

**Comment by ranjitjhala** [comment]
Niki That is a separate and orthogonal issue to the problem Rose has which
has to do with the coercion’s not getting appropriately substituted

**Comment by nikivazou** [comment]
I guess you are correct, but if we do not also address this issue, we cannot go far with GADTS.

**Comment by ranjitjhala** [comment]
Not sure what you are referring to. It is true that we cannot directly
include JDs in SMT lab, but for those situations we can just encode them as
we were before as an opaque integer.

**Comment by ranjitjhala** [comment]
haha -- as usual @nikivazou  is right; once the coercion-substitution issue is fixed, this hits a real road block because GADTs seem pretty incompatible with SMT-Sorts.

## Example

```haskell
data Field a where
  FInt  :: Field Int
  FBool :: Field Bool

{-@ reflect proj @-}
proj :: Field a -> a -> a
proj fld x = case fld of
               FInt  -> 1 + x
               FBool -> not b  
```

## The Problem

The problem is you cannot encode the body of `proj` as a well-sorted refinement.
The body looks like:

```haskell
    if is$FInt fld
        then (1 + x)   -- 'x' used as Int
        else (not x)   -- 'x' used as Bool
```

where `x` is now being treated both as `Int` and as a `Bool`. Now GHC has all sorts
of machinery to deal with the above; in Core the above is represented as:

```haskell
    if is$FInt fld
        then (1 + (coerce (a ~ Int)  x))
        else (not (coerce (a ~ Bool) x))
```

But of course there is no such thing in SMTLIB, so Z3 rejects formulas like the above.

## Approach: Uninterpreted Functions

One approach may be to encode a `coerce` as an explicit **uninterpreted function**.
These would yield well-sorted refinements, e.g.

```haskell
    if is$FInt fld
        then (1 + (coerce_a_int  x))
        else (not (coerce_a_bool x))
```

where we define, extra constants in the style of `apply` 

```haskell
   constant coerce_a_int  :: a -> int
   constant coerce_a_bool :: a -> int
```

However, it would not let us verify:


```haskell
{-@ reflect unwrap @-}
unwrap :: Field a -> a -> a
unwrap fld x = proj fld x

{-@ test :: _ -> TT @-}
test =  unwrap FInt  4    == 5
     && unwrap FBool True == False
```

because we'd get

```haskell
  unwrap FInt 4 :: { if is$FInt FInt then (1 + coerce_int_int 4) else ...  }
```

and the UIF nature of `coerce_int_int` renders the VC invalid.

## Solution: Eliminate Trivial Coercions

HOWEVER, the solution here, may simply be to use UIFs when the
coercion is non-trivial (e.g. `a ~ int`) but to eschew them when
they are trivial. That is we would encode:

| Expr                   | SMTLIB             |
|:-----------------------|:-------------------|
| `coerce (a ~ int) x`   | `coerce_a_int x`   |
| `coerce (int ~ int) x` | `x`                |

which, I imagine is what happens _somewhere_ inside GHC too?

**Comment by ranjitjhala** [comment]
## Example

```haskell
data Field a where
  FInt  :: Field Int
  FBool :: Field Bool

{-@ reflect proj @-}
proj :: Field a -> a -> a
proj fld x = case fld of
               FInt  -> 1 + x
               FBool -> not b  
```

## The Problem

The problem is you cannot encode the body of `proj` as a well-sorted refinement.
The body looks like:

```haskell
    if is$FInt fld
        then (1 + x)   -- 'x' used as Int
        else (not x)   -- 'x' used as Bool
```

where `x` is now being treated both as `Int` and as a `Bool`. Now GHC has all sorts
of machinery to deal with the above; in Core the above is represented as:

```haskell
    if is$FInt fld
        then (1 + (coerce (a ~ Int)  x))
        else (not (coerce (a ~ Bool) x))
```

But of course there is no such thing in SMTLIB, so Z3 rejects formulas like the above.

## Approach: Uninterpreted Functions

One approach may be to encode a `coerce` as an explicit **uninterpreted function**.
These would yield well-sorted refinements, e.g.

```haskell
    if is$FInt fld
        then (1 + (coerce_a_int  x))
        else (not (coerce_a_bool x))
```

where we define, extra constants in the style of `apply` 

```haskell
   constant coerce_a_int  :: a -> int
   constant coerce_a_bool :: a -> int
```

However, it would not let us verify:


```haskell
{-@ reflect unwrap @-}
unwrap :: Field a -> a -> a
unwrap fld x = proj fld x

{-@ test :: _ -> TT @-}
test =  unwrap FInt  4    == 5
     && unwrap FBool True == False
```

because we'd get

```haskell
  unwrap FInt 4 :: { if is$FInt FInt then (1 + coerce_int_int 4) else ...  }
```

and the UIF nature of `coerce_int_int` renders the VC invalid.

## Solution: Eliminate Trivial Coercions

HOWEVER, the solution here, may simply be to use UIFs when the
coercion is non-trivial (e.g. `a ~ int`) but to eschew them when
they are trivial. That is we would encode:

| Expr                   | SMTLIB             |
|:-----------------------|:-------------------|
| `coerce (a ~ int) x`   | `coerce_a_int x`   |
| `coerce (int ~ int) x` | `x`                |

which, I imagine is what happens _somewhere_ inside GHC too?

**Comment by ranjitjhala** [comment]
@rosekunkel can you make the example in 

   https://github.com/ucsd-progsys/liquidhaskell/issues/1424#issuecomment-473148952

self contained so I can try out the recent edits? Currently `RefinedFilter` is not defined...

The following tests work in the `ple2` branch:

https://github.com/ucsd-progsys/liquidhaskell/blob/ple2/tests/ple/pos/T1424.hs

https://github.com/ucsd-progsys/liquidhaskell/blob/ple2/tests/ple/pos/T1424A.hs
