### ISSUE TITLE
Crash SMTLIB2: Sorts Int and (Array Int Bool) are incompatible

### ISSUE THREAD

**Issue by dmalkr** [ucsd-progsys/liquidhaskell#1467]
When processing my file, `liquid` got this:

```
% liquid --prune-unsorted Thundermint/P2P.hs                                                                                                                                 :( ~p/thundermint
LiquidHaskell Version 0.8.6.0, Git revision 580aef36671058c9f8a28bf5900acf41d70b4f89 (dirty) no git information
Copyright 2013-19 Regents of the University of California. All Rights Reserved.

Targets: Thundermint/P2P.hs

**** [Checking: Thundermint/P2P.hs] ********************************************

**** DONE:  A-Normalization ****************************************************
 

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  Transformed Core ***************************************************
 
Working   5% [====.............................................................]

**** DONE:  annotate ***********************************************************
 

**** RESULT: ERROR *************************************************************


:1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 33932 column 1037: Sorts Int and (Array Int Bool) are incompatible"
```

Can you fix it?

And sorry, I can't get simple code for reproduce this error :( So, If this ticket useless, please, close it, I try other versions of LiquidHaskell

**Comment by ranjitjhala** [comment]
hmm sorry! This is definitely an LH bug, but cannot fix without code. I'll close but if you come across it on a shorter program please let me know. [Are you somehow using `Data.Set`?]

**Comment by googleson78** [comment]
I also have a very similar issue:
```
  crash: SMTLIB2 respSat = Error "line 16377 column 18944: Sorts Int and Bool are incompatible"
```
and I also don't have a short repro program :(. 

@dmalkr did you manage to find a fix/workaround?

Don't know if any of this will help but: It happens **somewhat** randomly because after playing for a bit and trying to get a small case it disappeared and some type mismatches appeared. After fixing them it reappared again. It also happened while checking different files the first time vs the second time. I am also using `--prune-unsorted`
