### ISSUE TITLE
Refinements on class instances are ignored (+ crash???)

### ISSUE THREAD

**Issue by googleson78** [ucsd-progsys/liquidhaskell#1498]
The following file:
```haskell
class A a where
  f :: a -> Int

instance A Int where
  {-@ f :: _ -> {x : Int | 0 < x} @-}
  f n = n

{-@ x :: {x : Int | 0 < x} @-}
x :: Int
x = f ((-1) :: Int)
```
is declared as `SAFE` by `liquid`.

The following is also declared as `SAFE`:
```haskell
class A a where
  f :: a -> Int

instance A Int where
{-@
instance A Int where
  f :: _ -> {x : Int | 0 < x}
@-}
  f n = (-1)
```

More interestingly the following generates a crash:
```haskell
class A a where
  f :: a -> Int

instance A Int where
{-@
instance A Int where
  f :: _ -> {x : Int | 0 < x}
@-}
  f n = (-1)

{-@ g :: Int -> {n : Int | 0 < n} @-}
g :: Int -> Int
g x = f x
```
Crash log:
```
 /tmp/liquid/class/Classes.hs:13:9: Error: Uh oh.

 13 | g x = f x
              ^

     addC: malformed constraint:
{lq_tmp$x##610 : GHC.Types.Int | lq_tmp$x##610 == x##aVJ}
 <:
{VV : _ | $HOLE[lq_tmp$db##0:=VV]}
```

Am I misunderstanding [this section](https://github.com/ucsd-progsys/liquidhaskell#modules-with-code-type-classes)?

**Comment by ranjitjhala** [comment]
Wow this is surprising to me!

I *think* what is happening here is that the signature for “f” is

1. Getting attached to the class method and
2. NOT getting checked at the instance.

However even if 1 is happening (counterintuitive, but possible because of
how name resolution happens) I don’t understand why 2 should happen?

**Comment by ranjitjhala** [comment]
Ok, here's what's happening, which is consistent with all the above.

1. When you don't write "instance" inside the `{-@ ... @-}` the spec is associated with the class,
2. When you write "instance" it is associated with the instance.

Either way, the text in [that section](https://github.com/ucsd-progsys/liquidhaskell#modules-with-code-type-classes) should be clarified to make explicit that we *never check instance signatures*. 
They are *always trusted*, and we just *use* the signatures at client "call" sites. 
I think this is a missing feature (and can lead to this kind of unsoundness). 

I _think_ we never got around to implementing this because its a bit hard 
to tell where they are created?

Regardless we should fix this ASAP!

**Comment by googleson78** [comment]
Could you give me an example of `2.`, I would do a pr with a documentation update?

Also is the crash related or is it an entirely different issue?

**Comment by googleson78** [comment]
Uh.. `liquid` doesn't like the following either:
```haskell
{-@
class A a where
  f :: _ -> {x : Int | 0 < x}
@-}
class A a where
  f :: a -> Int
```

with:
```
 /tmp/liquid/class/Classes.hs:(5,1)-(6,15): Error: Specified type does not refine Haskell type for `Main.C:A` (Plugged Init types new)

 5 | class A a where
 6 |   f :: a -> Int


 The Liquid type

     forall a . (a -> GHC.Types.Int) -> (Main.A a)

 is inconsistent with the Haskell type

     forall a. (a -> GHC.Types.Int) -> Main.A a

 defined at /tmp/liquid/class/Classes.hs:(5,1)-(6,15)

 Specifically, the Liquid component

     a

 is inconsistent with the Haskell component

     a


 HINT: Use the hole '_' instead of the mismatched component (in the Liquid specification)
```

**Comment by ranjitjhala** [comment]
@nikivazou you're looking into this, right?

**Comment by nikivazou** [comment]
Yes!

**Comment by ranjitjhala** [comment]
merci beaucoup!

<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
I'm using Inbox When Ready
<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
to protect my focus.

**Comment by nikivazou** [comment]
This should be fixed. @googleson78  can you pull develop and check if your initial example is ok?

**Comment by ranjitjhala** [comment]
Wow Thanks @nikivazou!!!!

**Comment by googleson78** [comment]
@nikivazou 
Here are my results with the three original examples:

## 0.  
```haskell
class A a where
  f :: a -> Int

instance A Int where
  {-@ f :: _ -> {x : Int | 0 < x} @-}
  f n = n

{-@ x :: {x : Int | 0 < x} @-}
x :: Int
x = f ((-1) :: Int)
```
Still declared as `SAFE`. (even though it shouldn't be?)

## 1.
```haskell
class A a where
  f :: a -> Int

instance A Int where
{-@
instance A Int where
  f :: _ -> {x : Int | 0 < x}
@-}
  f n = (-1)
```
Now generates a crash:
```
 <no location info>: Error: Uh oh.
     RefType.nlzP: cannot handle {VV : _ | $HOLE[lq_tmp$db##0:=VV]}
```

## 2. (the original crashing example)
```haskell
class A a where
  f :: a -> Int

instance A Int where
{-@
instance A Int where
  f :: _ -> {x : Int | 0 < x}
@-}
  f n = (-1)

{-@ g :: Int -> {n : Int | 0 < n} @-}
g :: Int -> Int
g x = f x
```
Now generates a different crash:
```
 <no location info>: Error: Uh oh.
     RefType.nlzP: cannot handle {VV : _ | $HOLE[lq_tmp$db##0:=VV]}
```

**Comment by nikivazou** [comment]
Well, none of these should get accepted, but in my PR I added proper error messages. 
That is
0. gets rejected since you cannot refine class methods without the `instance` or `class` syntax. 
1 and 2. are rejected because the type hole you use (`_`) is not resolved properly. Since the type hole is resolved wrt the specific instance LH cannot find it, but at least now there is an error message telling you to replace this hole with a type. Once you replace `_` with `Int` your example is soundly Unsafe.

Waiting for circle to accept my PR and then merge.

**Comment by ranjitjhala** [comment]
Super, thanks Niki !
