### ISSUE TITLE
SMT2LIB crash with non-eta-expanded Constructors

### ISSUE THREAD

**Issue by michaelborkowski** [ucsd-progsys/liquidhaskell#1687]
I have the following two small files which have boiled down from research code:

https://github.com/michaelborkowski/liquidmeta/blob/master/Lambda2/SMTTest.hs
https://github.com/michaelborkowski/liquidmeta/blob/master/Lambda2/SMTTest2.hs

The first file defines the data types for exprs and types and contains the types for Small Step proof trees and its transitive closure. The first file typechecks as SAFE. The second file imports the first and contains just a trivial Typing judgement type. Running LH on the second file fails with this error

```
:1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 1025 column 4065: Sort mismatch at argument #2 for function (declare-fun apply$35$$35$0 (Int Int) Int) supplied sort is (Array SMTTest.Expr SMTTest.Expr SMTTest.StepP)"
```

But Expr and StepP appear nowhere in the file except for this line at the top to import them into scope for LH:

```
semantics = (Step, EvalsTo)
```

If I remove this line and attempt to run `liquid SMTTest2hs` I get several errors that refer to the imported SMTTest.hs (which already checked as SAFE) along the lines of:

```
 SMTTest.hs:80:5-49: Error: Illegal type specification for `SMTTest.EApp1`

 80 |     EApp1 :: Expr -> Expr -> Step -> Expr -> Step
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

     SMTTest.EApp1 :: e:SMTTest.Expr -> e':SMTTest.Expr -> lqdc##$select##SMTTest.EApp1:{VV : SMTTest.Step | propOf VV == Step e e'} -> e1:SMTTest.Expr -> {VV : SMTTest.Step | EApp1 VV == e1
                                                                                                                                                                                && EApp1##lqdc##$select VV == lqdc##$select##SMTTest.EApp1
                                                                                                                                                                                && EApp1 VV == e'
                                                                                                                                                                                && EApp1 VV == e
                                                                                                                                                                                && propOf VV == Step (App e e1) (App e' e1)}
     Sort Error in Refinement: {VV : SMTTest.Step | propOf VV == Step e##SMTTest.EApp1 e'##SMTTest.EApp1}
     Unbound symbol Step --- perhaps you meant: len, prop ?


 SMTTest.hs:81:5-49: Error: Illegal type specification for `SMTTest.EApp2`
```

If I combine both files into one, it typechecks as SAFE.  So this only happens when there's an import.

**Comment by mystaroll** [comment]
Hi, the links you reported aren't working (probably your repo is private)

**Comment by michaelborkowski** [comment]
sorry, I've put the files on a public repo:

https://github.com/michaelborkowski/liquidmeta_public/blob/master/SMTTest.hs
https://github.com/michaelborkowski/liquidmeta_public/blob/master/SMTTest2.hs

**Comment by mystaroll** [comment]
I have a feeling this is related to the ADT encoding in LH, could you try running liquidhaskell with `--no-adt` or add `{-@ LIQUID "--no-adt" @-}` to both of your files?
Update: I tried it, with ```--no-adt``` it works

**Comment by ranjitjhala** [comment]
@michaelborkowski -- the ADT constructors like `Step` and `EvalsTo` are appearing _without_ being "eta-expanded" / "saturated" i.e. just as `Step` and `EvalsTo` instead of `Step x y` or `EvalsTo x y` -- which is what is freaking the SMT solver out.

1. *Right now* you can work around it by replacing the line

```haskell
semantics = (Step, EvalsTo)
```

to 

```haskell
semantics = (\x y -> Step x y, \x y -> EvalsTo x y)
```

2. In the *short term* the code in `CoreToLogic.hs` should do this eta-expansion automatically, at least at the refinement level, somehow. (Not clear what the best strategy is -- maybe we should _seriously_ look into SMT support for lambdas.)

3. In the *long term* its silly to have to put in these **dummy imports** -- @adinapoli and @kosmikus  -- this is something we discussed, IDK if you have any thoughts, the problem 
is the following


`module Lib`

* defines a datatype `T` with constructor `C`
* REFLECTS a function `foo` (or another datatype `T2` with ctor `C2`) *whose refinement* uses `C`

Now, module `Lib` checks just fine

`module Client`

* imports `Lib` 

and LH crashes when resolving the _reflected_ definition of `foo` or `C2` because the name `C` is *not in scope* :-(

We have been working around this by forcibly-importing `C` by adding a line

```
dummy = (C, ...)
```

but this is painful at the least... Any ideas?

**Comment by ranjitjhala** [comment]
@michaelborkowski when you get a chance, can you check if this was fixed by the recent PRs

 #1857 and #1858

(which will both soon be in `develop`)

**Comment by michaelborkowski** [comment]
While the specific problem mentioned in the issue -- that constructors like Step need to be eta-expanded or fully applied -- is not resolved by these merged pull requests, the underlying problem has been resolved.  There's been no need for a while now to include these dummy assignments like `imports = (Step, EvalsTo)` because that underlying problem got fixed at some point. So I'm closing the issue.
