### ISSUE TITLE
liquid-legacy and liquid plugin behave differently

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1708]
in this example: https://gist.github.com/nikivazou/6932d10899f30e34a430c3e9978eaf9c

```
>> liquid-legacy tests/todo/fixme.hs # says SAFE 
>> stack exec -- liquid tests/todo/fixme.hs # crashes with SMTLIB2 error 
```

If I change the below definitions (of https://gist.github.com/nikivazou/6932d10899f30e34a430c3e9978eaf9c#file-fixme-hs-L11-L12) 

```
bool1 = undefined -- not supported by the plugin, but ok for the old LH
bool2 = undefined -- if changed to True it is ok by the plugin as well
```

to 

```
bool1 = True 
bool2 = True
```

both agree to SAFE. 

@ranjitjhala @adinapoli

**Comment by ranjitjhala** [comment]
I’m surprised the old LH handled it: I didn’t think we supported
“undefined” in reflected functions?

**Comment by nikivazou** [comment]
Yes, though it is not directly reflected. 
1. It would be convenient to support that
2. I am still surprised that the two ways give different response.

**Comment by ranjitjhala** [comment]
What is the exact error you get?

**Comment by kosmikus** [comment]
I've been looking at this briefly.

The error message with the plugin is:
```
**** LIQUID: ERROR :1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 708 column 54421: invalid qualified identifier, sort mismatch" 
```
That's not a very helpful error message from z3, but perhaps that is normal. (I would hope it actually tells which identifier, but it doesn't. I'm not sure exactly how the line/column calculation works here either.)

I've then been looking at the actual stuff that's being sent between LH and z3 (which unfortunately does not seem traceable without changing the program; is this so rarely needed?), but I'm seeing rather substantial differences.

I guess the main candidate for differences is that the base library specs are included differently between the old and the new system. Possibly the plugin is somehow not including an instruction that the old system has. I think I'll need @adinapoli 's much better knowledge about the changes he has made for the plugin to make progress on this, but he's only going to be back on LH work on Monday.

**Comment by adinapoli** [comment]
Indeed, this is peculiar and interesting. The only two places where divergences might occur are either in the way we provide specs (and how we provide them) as Andres was suggesting, or in the way we create a `GhcSrc` before turning it into a `LiftedSpec`. Perhaps somehow those `bool1` and `bool2` are being filtered out (or transformed) by the `GHC.Interface` but treated differently by the `GHC.Plugin`.

Anyway, I will know more about this on Monday, and report back 😉

**Comment by adinapoli** [comment]
@nikivazou @ranjitjhala Ok, I've got to the bottom of this, and here is a somewhat succinct explanation of the problem, to serve as a _post mortem_. First of all, the offending line of that cryptic crash error can be found by looking inside the annotation file produced as part of `.liquid/Fixme.hs.smt2`, which revealed that the solver was crashing due to:

```
(= Fixme.bool2 (as GHC.Err.undefined Bool))
```

I will spare you the painful details, but the culprit has to be researched in the fact that _the plugin and the executable generate slightly different core binds for this file_. In particular, for the _plugin_, the optimiser generates the following (for `bool2`):

```
 bool2 :: Bool
 [
      LclIdX
    ,
  Unf=Unf{
        Src=<vanilla>
      , TopLvl=True
      , Value=False
      , ConLike=False
      ,
          WorkFree=False
      , Expandable=False
      , Guidance=IF_ARGS [] 20 0
    }
  ]
 bool2
   = break<5>()
     src<../fixme.hs:12:1-17> undefined @ 'LiftedRep @ Bool $dIP_a1H1
```

Whereas for the executable a long nested chain of `let` s (sorry for the wall of text):

```
 bool2 :: Bool
 [
      LclIdX
    ,
  Unf=Unf{
        Src=<vanilla>
      , TopLvl=True
      , Value=False
      , ConLike=False
      ,
          WorkFree=False
      , Expandable=False
      , Guidance=IF_ARGS [] 430 0
    }
  ]
 bool2
   = let {
      lq_anf$##7205759403792800156 :: Addr#
       [LclId]
       lq_anf$##7205759403792800156 = "undefined"# 
  } in
     let {
      lq_anf$##7205759403792800157 :: [Char]
       [LclId]
       lq_anf$##7205759403792800157
         = unpackCString# lq_anf$##7205759403792800156 
  } in
     let {
      lq_anf$##7205759403792800158 :: Addr#
       [LclId]
       lq_anf$##7205759403792800158 = "main"# 
  } in
     let {
      lq_anf$##7205759403792800159 :: [Char]
       [LclId]
       lq_anf$##7205759403792800159
         = unpackCString# lq_anf$##7205759403792800158 
  } in
     let {
      lq_anf$##7205759403792800160 :: Addr#
       [LclId]
       lq_anf$##7205759403792800160 = "Fixme"# 
  } in
     let {
      lq_anf$##7205759403792800161 :: [Char]
       [LclId]
       lq_anf$##7205759403792800161
         = unpackCString# lq_anf$##7205759403792800160 
  } in
     let {
      lq_anf$##7205759403792800162 :: Addr#
       [LclId]
       lq_anf$##7205759403792800162
         = "/Users/adinapoli/work/fixme.hs"# 
  } in
     let {
      lq_anf$##7205759403792800163 :: [Char]
       [LclId]
       lq_anf$##7205759403792800163
         = unpackCString# lq_anf$##7205759403792800162 
  } in
     let {
      lq_anf$##7205759403792800164 :: Int#
       [LclId]
       lq_anf$##7205759403792800164 = 12# 
  } in
     let {
      lq_anf$##7205759403792800165 :: Int
       [LclId]
       lq_anf$##7205759403792800165 = I# lq_anf$##7205759403792800164 
  } in
     let {
      lq_anf$##7205759403792800166 :: Int#
       [LclId]
       lq_anf$##7205759403792800166 = 9# 
  } in
     let {
      lq_anf$##7205759403792800167 :: Int
       [LclId]
       lq_anf$##7205759403792800167 = I# lq_anf$##7205759403792800166 
  } in
     let {
      lq_anf$##7205759403792800168 :: Int#
       [LclId]
       lq_anf$##7205759403792800168 = 12# 
  } in
     let {
      lq_anf$##7205759403792800169 :: Int
       [LclId]
       lq_anf$##7205759403792800169 = I# lq_anf$##7205759403792800168 
  } in
     let {
      lq_anf$##7205759403792800170 :: Int#
       [LclId]
       lq_anf$##7205759403792800170 = 18# 
  } in
     let {
      lq_anf$##7205759403792800171 :: Int
       [LclId]
       lq_anf$##7205759403792800171 = I# lq_anf$##7205759403792800170 
  } in
     let {
      lq_anf$##7205759403792800172 :: SrcLoc
       [LclId]
       lq_anf$##7205759403792800172
         = SrcLoc
             lq_anf$##7205759403792800159
             lq_anf$##7205759403792800161
             lq_anf$##7205759403792800163
             lq_anf$##7205759403792800165
             lq_anf$##7205759403792800167
             lq_anf$##7205759403792800169
             lq_anf$##7205759403792800171 
  } in
     let {
      lq_anf$##7205759403792800173 :: ([Char], SrcLoc)
       [LclId]
       lq_anf$##7205759403792800173
         = (lq_anf$##7205759403792800157, lq_anf$##7205759403792800172) 
  } in
     let {
      lq_anf$##7205759403792800174 :: ?callStack::CallStack
       [LclId]
       lq_anf$##7205759403792800174
         = emptyCallStack
           `cast` (
        Sym (N:IP[0] <"callStack">_N <CallStack>_N)
                   :: Coercible CallStack (?callStack::CallStack)
    ) 
  } in
     let {
      lq_anf$##7205759403792800175 :: CallStack
       [LclId]
       lq_anf$##7205759403792800175
         = lq_anf$##7205759403792800174
           `cast` (
        N:IP[0] <"callStack">_N <CallStack>_N
                   :: Coercible (?callStack::CallStack) CallStack
    ) 
  } in
     let {
      lq_anf$##7205759403792800176 :: CallStack
       [LclId]
       lq_anf$##7205759403792800176
         = pushCallStack
             lq_anf$##7205759403792800173 lq_anf$##7205759403792800175 
  } in
     let {
      $dIP_a1Gr :: HasCallStack
       [
        LclId
      ,
        Unf=Unf{
          Src=<vanilla>
        , TopLvl=False
        , Value=False
        , ConLike=False
        ,
                WorkFree=False
        , Expandable=False
        , Guidance=IF_ARGS [] 400 0
      }
    ]
       $dIP_a1Gr
         = lq_anf$##7205759403792800176
           `cast` (
        Sym (N:IP[0] <"callStack">_N <CallStack>_N)
                   :: Coercible CallStack (?callStack::CallStack)
    ) 
  } in
     break<5>()
     src</Users/adinapoli/work/fixme.hs:12:1-17>
     undefined @ 'LiftedRep @ Bool $dIP_a1Gr

```

This is **crucial**, because later on, when we generate the constraints as part of the [consCB](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Constraint/Generate.hs#L450-L453) function , we call `extender` on a "singleton" `SpecType` , but we also crucially call `simplify` over the `CoreExpr` we are currently processing.
`simplify` is defined like this:

```haskell
simplify :: CoreExpr -> CoreExpr
simplify (Tick _ e)       = simplify e
simplify (App e (Type _)) = simplify e
simplify (App e1 e2)      = App (simplify e1) (simplify e2)
simplify (Lam x e) | isTyVar x = simplify e 
simplify e                = e
```

And later on, we rely on its result in a guard of `makeSingleton`:

```haskell
makeSingleton :: CGEnv -> CoreExpr -> SpecType -> SpecType
makeSingleton γ e t
  | higherOrderFlag γ, App f x <- simplify e
  = case (funExpr γ f, argForAllExpr x) of     --- PLUGIN ENTERS HERE    
      (Just f', Just x')
                 | not (GM.isPredExpr x) -- (isClassPred $ exprType x)
                 -> strengthenMeet t (uTop $ F.exprReft (F.EApp f' x'))
      (Just f', Just _)
                 -> strengthenMeet t (uTop $ F.exprReft f')
      _ -> t
  | rankNTypes (getConfig γ)
  = case argExpr γ (simplify e) of
       Just e' -> strengthenMeet t $ (uTop $ F.exprReft e')
       Nothing -> t
  | otherwise
  = t   --- EXECUTABLE ENTERS HERE
  where 
    argForAllExpr (Var x)
      | rankNTypes (getConfig γ)
      , Just e <- M.lookup x (forallcb γ)
      = Just e
    argForAllExpr e
      = argExpr γ e
```

This means that for the legacy executable we do not "mangle" the input type `GHC.Types.Bool` (attached to `bool2`) but for the plugin we transform its `true` refinement into `VV == GHC.Err.undefined` as part of the call to `uTop $ F.exprReft e'`. 

But why is that? Simple, because when we call simplify in the first guard, for the plugin we have a nice "flat" `bool2`, so we match `App` and we carry along. However, for the executable, **our CoreExpr is a Let, and simplify doesn't handle directly the Let case**, which means that `simplify` in that case is a no-op.

To prove this, we can quickly change the `simplify` definition to simplify let bindings, like this:

```haskell
simplify :: CoreExpr -> CoreExpr
simplify (Tick _ e)       = simplify e
simplify (App e (Type _)) = simplify e
simplify (App e1 e2)      = App (simplify e1) (simplify e2)
simplify (Lam x e) | isTyVar x = simplify e 
simplify (Let _ e )       = simplify e 
simplify e                = e
```

And now.. tada! We would get the same behaviour for both the plugin and the executable, and we would incorrectly attach the wrong refinement in both cases (using a strategic `tracepp`):

```
Trace: [
  consCB.NonRec.after.extender 
  var = Fixme.bool2 
  binds = 251 := Fixme.bool2 : {VV##2008 : bool | VV##2008 == GHC.Err.undefined}
                ] : ()

... and for the executable

Trace: [
          consCB.NonRec.after.extender var = Fixme.bool2 
          binds = 151 := Fixme.bool2 : {VV##990 : bool | VV##990 == GHC.Err.undefined}
      ] : ()
```


Having said that, I am not sure how to proceed from here. It seems to me that perhaps that `simplify` function should at least document if the omission of `Let` was intentional, and why. Secondly, we would need to understand how we can mitigate the difference between the `CoreBind`s generated by the plugin vs the (legacy) executable. I think that we might never get to a place where we can generate _exactly_ the same binds (due to the stateful nature of the GHC API) but perhaps there is some wiggle room.

**Comment by ranjitjhala** [comment]
This is great @adinapoli! Lets not change `simplify` -- as I said the bug here is not that `undefined` is *failing* in one case, but that it is in fact *working* in the other case -- as discussed on slack, this is because it is somehow getting added to the refinement-wellformedness environment in `Bare.ghcSpecEnv` which is then used inside `Bare.Check` -- whereas in fact it shouldn't...


Note there are multiple environments.

- `ghcSpecEnv` is used to determine what is valid in the refinements
- `CGEnv` is used to determine what is valid in the code

So the `CGEnv` will contain binders for ALL the names in scope, and all their (refinement) types, but
the ghcSpecEnv will only contain the SUBSET of names that are allowed in refinements.

So the name `undefined` for example, is allowed to appear in the code of course, but not in the refinements.
