### ISSUE TITLE
optparse-applicative-0.16.0.0 works just fine

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquidhaskell#1751]
The Cabal file excludes optparse-applicative-0.16.0.0 from being used as a dependency. When I ignore that constraint, however, the build works just fine with optparse-applicative-0.16.0.0. Would it be possible to please lift that constraint in the Cabal file?

**Comment by ranjitjhala** [comment]
Sure, can you send a PR? (That will trigger the CI which will help double
check?) many thanks! Ranjit.

**Comment by adinapoli** [comment]
Ah, so that constraint has a "history": we originally added it because otherwise `optparse-simple` couldn't be built, but after [I filed an issue](https://github.com/fpco/optparse-simple/issues/14) Micheal released a new version.

I think it's fine to remove the constraint on `optparse-applicative`, but perhaps it's worth adding a lower bound on `optparse-simple` to make sure things keep building? I cannot remember exactly on which bits of `optparse-simple` we are relying upon, but it would nice at some point in the future to drop the dependency and simply rewrite the CLI code to use just `optparse-applicative`.
