### ISSUE TITLE
LH makes an erroneous type inference

### ISSUE THREAD

**Issue by jaredgreen2** [ucsd-progsys/liquidhaskell#1765]
for a function defined by conditions on the input, the inferred and required type of the input in those contexts doesnt take those conditions into account.
for example
{-@ fib :: {n:int | n >=0} -> {m:int | m>=n} @-}
fib 0 = 1
fib 1 = 1
fib n = fib(n-2) + fib(n-1)   --this line is, according to LH, type mismatched, though the type of n here should be {W:int | w>=2}

**Comment by ranjitjhala** [comment]
Hi @jaredgreen2 -- this is a subtle issue that I should try to write up properly.
The problem is that the specification for 

```
 {-@ fib :: {n:int | n >=0} -> {m:int | m>=n} @-}
```

while true, is not _inductive_  -- i.e. is not strong enough to be _provable_ 
using the strategy the LH and similar verifiers use for recursive functions.
In particular, in the case:

```
fib n = fib(n-2) + fib(n-1)
```

the only thing LH "knows" (from the spec of `fib`) is:

```
fib (n-2) >= (n-2)
fib (n-1) >= (n-1)
```

and that is not enough to prove that:

```
fib (n-2) + fib (n - 1) >= (n - 2) + (n-1) >= n
```

as of course `2n - 3` is _not_ always greater than `n`. (e.g. when `n == 2`)

Instead if you change the spec to:

``` 
{-@ fib :: {n:int | n >=0} -> {m:int | m>=n && m >= 1} @-}
```

then it _strengthens_ it and makes it provable.
