### ISSUE TITLE
plain unqualified haskell type is rejected as invalid when written as liquid type

### ISSUE THREAD

**Issue by RCoeurjoly** [ucsd-progsys/liquidhaskell#1842]
As I understand Liquid Haskell, a Haskell type is also a Liquid Haskell type.

When I load the following snippet:
```

halve                :: Int -> [a] -> ([a], [a])
halve 0 xs       = ([], xs)
halve n (x:y:zs) = (x:xs, y:ys) where (xs, ys) = halve (n-1) zs
halve _ xs       = ([], xs)
```

I don't get any errors.
However, I get errors with the following:

```
{-@ halve          :: Int -> [a] -> ([a], [a]) @-}
halve 0 xs       = ([], xs)
halve n (x:y:zs) = (x:xs, y:ys) where (xs, ys) = halve (n-1) zs
halve _ xs       = ([], xs)

```

> /home/drcoeurjoly/Exocortex/master/VA/Session_20/halve.hs:1:23: error:
>     • Specified type does not refine Haskell type for `Main.halve` (Plugged Init types old)
> The Liquid type
> .
>     GHC.Types.Int -> [a] -> ([a], [a])
> .
> is inconsistent with the Haskell type
> .
>     forall a1 a2 ->
> (GHC.Classes.Eq a1, GHC.Num.Num a1) =>
> a1 -> [a2] -> ([a2], [a2])
> .
> defined at /home/drcoeurjoly/Exocortex/master/VA/Session_20/halve.hs:3:1-5
> .
> Specifically, the Liquid component
> .
>     GHC.Types.Int
> .
> is inconsistent with the Haskell component
> .
>     a
> .
> 
> HINT: Use the hole '_' instead of the mismatched component (in the Liquid specification)
>     • 
>   |
> 1 | {-@ halve          :: Int -> [a] -> ([a], [a]) @-}
>   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^
> Failed, no modules loaded.

Any ideas why?

**Comment by ranjitjhala** [comment]
The problem is that:

1. GHC is oblivious to all LH signatures, so it types `halve` as if there is _no_ type annotation, as

```haskell
halve :: (Eq a, Num a) => a -> [b] -> [b]
```

2. LH insists that the LH types match (i.e. "refine") the GHC type, which is not the case here, as indicated by the error.

In practice I've found the easiest way is to write the GHC type and then add refinement annotations as needed e.g.

```haskell
{-@ halve :: _ -> [a] -> ([a], [a]) @-}
```

will work just fine here, as the error indicates.  LMK if this helps!
