### ISSUE TITLE
LiquidHaskell unbound data constructor selector?

### ISSUE THREAD

**Issue by njayinthehouse** [ucsd-progsys/liquidhaskell#1909]
Here's a snippet for returning the length of an array from its bounds.

```
module Array where

{-@ type Nat = {i:Int | 0 <= i} @-}

{-@ data Array a id = Array {
      unwrap :: [a],
      leftBound :: Nat,
      rightBound :: {j:Nat | leftBound <= j}
    } @-}
data Array a id = Array {
  unwrap :: [a],
  leftBound :: Int,
  rightBound :: Int
} deriving Eq

{-@ inline length @-}
{-@ length :: Array a id -> Nat @-}
length :: Array a id -> Int
length (Array _ i j) = j - i + 1
```
It fails with this error:
```
Illegal type specification for `Array.length`
                                        Array.length :: forall a b .
                                                        x1:(Array.Array a b) -> {VV : GHC.Types.Int | VV == (lqdc##$select x1 - lqdc##$select x1) + 1
                                                                                                      && VV >= 0}
                                        Sort Error in Refinement: {VV : int | (VV == (lqdc##$select##Array.Array##3 lq_tmp$db##0 - lqdc##$select##Array.Array##2 lq_tmp$db##0) + 1
                                                                               && VV >= 0)}
                                        Unbound symbol lqdc##$select##Array.Array##3 --- perhaps you meant: Array.Array ?
```
It seems like LH isn't creating the record selector `lqdc##$select##Array.Array`, but is still trying to use it internally?

This example uses the liquid binary for version 0.8.10.2.

**Comment by facundominguez** [comment]
This program would need `{-@ LIQUID "--exact-data-cons" @-}`. But from the user experience point of view it would be nice if LiquidHaskell could figure out on its own how to generate the selectors (or use the existing ones) instead of involving the user in enabling a flag.

In the short term, perhaps reversing the flag would do, so selectors are created by default and we have a flag "--no-data-cons-selectors" to turn it off. I think someone has suggested this elsewhere.

**Comment by njayinthehouse** [comment]
Adding the flag doesn't change the error, unfortunately.

**Comment by njayinthehouse** [comment]
But adding the `--exact-data-cons` *and* `--no-adt` does suffice.
