### ISSUE TITLE
Cannot build liquidhaskell-0.8.10.7 hackage package

### ISSUE THREAD

**Issue by ricardopenyamari** [ucsd-progsys/liquidhaskell#1950]
After downloadding the package, I do:
$cabal v2-build
and get: "The package directory './liquid-fixpoint' does not contain any .cabal file."

In fact, this directory is empty
I am using cabal  version 3.6.2.0

**Comment by ranjitjhala** [comment]
That's very odd! Have you tried using it via the plugin mode as demonstrated here?

https://github.com/ucsd-progsys/lh-plugin-demo

**Comment by facundominguez** [comment]
The [cabal.project](https://github.com/ucsd-progsys/liquidhaskell/blob/27bb4de8c45738f792094484c05d5f77b6776e25/cabal.project) file refers to the `liquid-fixpoint` directory rather than to the repo.

I imagine that downloading the package manually from hackage and then building it is not the most common scenario, but could be fixed still by having it refer to the `liquid-fixpoint` repo instead.

**Comment by facundominguez** [comment]
`cabal.project` is not included anymore in the hackage releases of `liquidhaskell`.
