### ISSUE TITLE
Add a plugin flag to signal expected failures

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#1980]
Tests of verification failures currently require to parse the output of compilation failures to check that the errors are the expected ones. If the plugin offered a flag to specify which failures are expected, then the output wouldn't have to be parsed. This would be another step to simplify the testsuite. 

I'm proposing that we add flags
* --expectErrorIncluding "some string" 
* --expectAnyError

The following has verification fail only if no verification failures are found.
```
{-@ LIQUID "--expectAnyError" @-}
```

The following has verification fail only if an error message does not include either letters `a` or `b`.
```
{-@ LIQUID "--expectErrorIncluding \"a\"" @-}
{-@ LIQUID "--expectErrorIncluding \"b\"" @-}
```

In principle, all expected errors are suppressed in the output. This will help the testsuite printing in the output only the errors that aren't expected. We could add later on a flag `--noSuppressExpectedErrors` to have them printed to stderr if needed.

**Comment by Fizzixnerd** [comment]
This looks good!  One thing that might simplify things is if we only allow the flag once, at least at first.  I don't expect the use-case of "fails with X *or* fails with Y" to come up very often, but I could be wrong.

**Comment by facundominguez** [comment]
> I don't expect the use-case of "fails with X or fails with Y" to come up very often, but I could be wrong.

Ok, but then we have to change the meaning of `--expectErrorIncluding "some string"` to `--expectAtLeastOneErrorIncluding "some string"`. It must be common for a test to fail with multiple verification errors.

Update: We discarded this option in later conversations since we do want to make sure that no new errors appear.

**Comment by Fizzixnerd** [comment]
I have been working on this issue.  So far I have the filtering logic down, I think.  I have a bunch of tests; not sure if there is a place already for unit tests in `liquidhaskell` that aren't source files checked by the plugin.  If not, I'll make a new suite.

I changed the code that folds over the pragmas to do them all at once.  Before it would iteratively do them, and this would break list-like arguments that can be supplied more than once.  I also spent a bunch of time chasing down a _second_ reason the flag wasn't showing up, and that's because I didn't realize Liquid has two configs: a module config, and a global config.  The global config is formed from (I believe) `LIQUID_OPTS` and command line flags, while the module config includes the pragmas specific to that file.  I was using the global config in a number of places, but was using pragmas to control the option, so it wasn't working.

[In any case, the fact that certain pragmas don't work except when provided on the command line (the list like ones) could be a reason why I couldn't get Text working in the benchmarks.  I will have to revisit, but I have vague memories of trying to use `idirs` from inside a file pragma.]

Now I am able to catch all errors with `{-@ LIQUID "--expect-error-containing=" @-}`.  I will alias this behavior to the `--expect-any-error` flag a little later.  For now, I have another major part to work on: making it succeed ONLY IF there is the specified error.  (I have the other direction mostly done, now.)

I spoke with @facundominguez about this, and he noted that even though errors can be caught in multiple locations (the `gcatch`es in Plugin.hs, or the regular `reportResult` function (also in Plugin.hs)), we should terminate the plugin for that file immediately if we don't have an exhaustive filter of all the errors in any *one* of those places.  This is because the program would have terminated anyways at that point, so the errors we see coming out of Liquid can't include "later" errors as I was worried it could.  I can either throw a unique exception that I catch at the top level, or use `Maybe/Either`s.  I'm leaning towards the `Maybe`s because I don't like throwing exceptions from possibly-pure code, and it seems like a cleaner solution.

**Comment by Fizzixnerd** [comment]
I have finished the opposite direction... mostly, I'm realizing slowly.  Please see the linked PR.

I opted for essentially an `Either ()` (which is isomorphic to `Maybe`, but more extensible should we need to make further changes in the future).

I say "mostly" because it's not quite an `iff` at this point.  What I think would be desirable is:

```
if each filter matches at least one error message and all error messages are filtered somehow then exit successfully.
if at least one filter does not match any error messages or if at least one message does not get filtered then exit with failure.
```

Currently, we instead have

```
if all error messages are filtered somehow (i.e., not necessarily using each filter at least once) then exit successfully.
if at least one error message is not filtered, then exit with failure.
```

This is quite different, and needs changing, I believe.  Basically, I need to keep track of which filters have matched, and throw an error if at least one is extraneous.

**Comment by facundominguez** [comment]
> if each filter matches at least one error message and all error messages are filtered somehow then exit successfully. if at least one filter does not match any error messages or if at least one message does not get filtered then exit with failure

I agree that this is what we need.

**Comment by Fizzixnerd** [comment]
I have fixed the issue mentioned above.  It is a true iff now.  What remains:

- move the `frew` (`filterReportErrorsWith`) tests to their own place in the code.
- Golden-ify the old negative tests by reporting the _current_ location of their failure into a flag in each file.  This would be as simple as adding a `--expect-error-containing='42:123'` where 42:123 is the line/column number of the _current_ error for that file.  This should not be particularly difficult with the parsing framework we already have, and will be the last good use of it, I suppose.  Alternatively, we could just leave the tests as-is and add the --expect-any-error flag.  I do not like this, as it makes it less likely for me to believe that nothing bad has happened to the tests between `develop` and this change's `HEAD`.  @facundominguez, thoughts?

**Comment by Fizzixnerd** [comment]
I have added the unit tests to the test suite, and started to run them in the CI along with (what I'm now calling) the integration tests (i.e. the tests where Liquid is directly run as a plugin on the source files).

In addition, I added a `--expect-any-error` flag and updated the filtering code to allow for an `AnyFilter`.

I got HLS working on the liquidhaskell source code, and my life is much easier because of it.  I will have a PR to delete the old HLint.hs soon, as this is necessary (hlint no longer accepts source files, you _must_ use the yaml file format, and HLS crashes if this file is present).

**Comment by Fizzixnerd** [comment]
I have begun migrating the test suite to the new non-parsing simpler program interface.  We shall see how it fairs in terms of usability, as we will lose our summarizing capability (at least at first).  However, the parallelization is nice!

**Comment by Fizzixnerd** [comment]
Cabal 810 passes the CI, but Cabal 900 fails on stitch-lh

**Comment by Fizzixnerd** [comment]
Removed modify-tests and dead code from driver.  Made parsing-errors it's own thing.  Fix stack 810
