### ISSUE TITLE
Have stack builds honor LIQUID_DEV_MODE=true

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#2027]
The command
```
LIQUID_DEV_MODE=true cabal build
```
skips rebuilding `liquid-*` libraries.

For some unknown reason
```
LIQUID_DEV_MODE=true stack build
```
rebuilds the `liquid-*` libraries anyway. This is known to happen in NixOS and MacOS.

This issue is about investigating and fixing this behavior, so `stack` builds can also skip rebuilding `.liquid-*` libraries.

**Comment by facundominguez** [comment]
I had another look at this. `cabal-install` relinks the setup script of `liquid-*` and then skips building the libraries.

`stack` does almost the same in NixOS if I additionally pass `--no-nix-pure` on the command-line, except that it also unregisters the `liquid-*` packages before attempting to build. So after skipping the building of `liquid-*`, it needs to copy and register the packages again. The only improvement here would be to ask `stack` to avoid unregistering, but the speed up would be rather marginal when compared to `cabal-install`, I believe.

@plredmond, do you actually see Haskell modules from `liquid-*` rebuilt in MacOS when using `LIQUID_DEV_MODE=true stack build`?

**Comment by plredmond** [comment]
Hi Facundo. Sorry for the late response. It does seem to be resolved. I tried running both *without* and *with* the envvar to show you the time and log output. Here is my procedure, with logs attached:

* Delete `.stack-work/`
* Leave `LIQUID_DEV_MODE` unset in the environment
* ```python
  stack_build = subprocess.check_output(['time', 'stack', 'build'], stderr=subprocess.STDOUT)
  ```
* [stack_build.txt](https://github.com/ucsd-progsys/liquidhaskell/files/9118051/stack_build.txt)
* Modify one line of code in `src/Language/Haskell/Liquid/Liquid.hs`
* ```python
  stack_build_dev = subprocess.check_output(['time', 'env', 'LIQUID_DEV_MODE=true', 'stack', 'build'], stderr=subprocess.STDOUT)
  ```
* [stack_build_dev.txt](https://github.com/ucsd-progsys/liquidhaskell/files/9118052/stack_build_dev.txt)

The first log takes 350s, and the second 40s. The second log reports that it's unregistering the dependent packages, and so that's why I thought it was rebuilding them originally. I think now it might be just linking them.

**Comment by facundominguez** [comment]
Thanks for your experiments @plredmond. I'm closing this issue then, as it seems we have something close enough to the optimal.
