### ISSUE TITLE
LH loses refinements on @-patterns, fails to establish refinement in branch

### ISSUE THREAD

**Issue by plredmond** [ucsd-progsys/liquidhaskell#2098]
```haskell
{-@ LIQUID "--no-totality" @-}

data Peano = PlusOne Peano | Zero

{-@
broken1 :: {p:Peano | p /= Zero} -> Int @-}
broken1 :: Peano -> Int
broken1 (PlusOne Zero) = 1
borken1 (PlusOne p@PlusOne{}) = 1 + broken1 p -- LH doesn't know that `p` is constructed with PlusOne

{-@
broken2 :: {p:Peano | p /= Zero} -> Int @-}
broken2 :: Peano -> Int
broken2 (PlusOne p) =
    case p of
        Zero -> 1
        PlusOne{} -> 1 + broken2 p -- LH doesn't know that `p` is constructed with PlusOne in this branch
```

I think there's three issues here
* `broken1` shows that the @-pattern isn't bound with the information established by the pattern
* `broken2` shows that you can't refine (GHC sense) information known about a binder by casing on it

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1667961531_14444.hs

In the online LH demo, adding `--exact-data-cons` fixes the issue, however I have that flag enabled on my local project and this issue is occurring.

**Comment by ranjitjhala** [comment]
Odd that the issue is occurring with `--exact-data` it shouldn't!

Other than that though, without exact-data, LH doesn't know that
the `PlusOne z /= Zero` (that's one of the main things exact-data
does -- not related to the @-pattern at all. You can tell it, with
an explicit measure, e.g. see this variant

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1667968283_14454.hs

**Comment by plredmond** [comment]
Thanks for clarifying!
