### ISSUE TITLE
Combine GHC and Liquid Type Aliases

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#381]
It would be nice if we could reject:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/todo/alias.hs

**Comment by ranjitjhala** [comment]
Btw, @spinda if we can do this, we can get *halfway* to your proposal of encoding specifications
with plain GHC types. I say "halfway" because then specifications would be split into two parts:

1. **Type definitions**, where there would still be duplication, e.g.

```
{-@ type Nat = {v:Int | 0 <= v} @-}
type Nat = Int

{-@ type Fin x = {v:Int | v < z} @-}
type Fin x = Int
```

2. **Type Specifications** where there is no duplication, e.g.

```
decr :: x@Nat -> Fin x
```

(Where `type t1 @ t2 = t2`)

**Comment by spinda** [comment]
In order to fix this we definitely need to make LiquidHaskell aliases module-scoped instead of global. Otherwise, declaring a type synonym anywhere, in-scope or not, would break same-named LiquidHaskell aliases in other modules.

I like the definitions vs. specifications approach a lot. I think aliases would work best as refinements on Haskell synonyms instead of existing only in LiquidHaskell, as it (a) lets GHC handle the scoping for us and (b) fixes the issues we were discussing earlier with type synonyms and using type variables for binders.

(Also, I really like the usage of `@`, but unfortunately it's not a valid operator either...)

**Comment by ranjitjhala** [comment]
How about `#` ? That doesn't look too bad. Now of course, the *second* half would be to figure out some crafty TF encoding for the *specifications* themselves, e.g. some way of defining the 

```
type Fin x = {v:Int | v < z}
```

Which would let us reuse GHC's machinery for modularizing alias names etc.

**Comment by ranjitjhala** [comment]
Btw, I am a bit concerned that once we have measures, it will get clunky to specify refinements with TF.
For example, what would

```
type ListNE a = {v:[a] | len v > 0}
```

look like? As I understand it (?), there is no support for type-level lambdas or such. (In general we could imagine various encodings, e.g. `len v` would become `apply "len" "v"` -- which is itself messy because
we'd want to merge type-level `Nat` and `Symbol` into a single type level `Expr`, which would require
further syntactic noise. Wonder if its easier to just do something (ok, I admit, super hacky!) like encoding
the refinements as a single monolithic type level string, so:

```
type ListNE a = Refine [a] "v" "0 < len v"
```

where we have simply:

```
type Refine t (v::Symbol) (r::Symbol) = t
``` 

Now, as long as GHC can hold onto the actual literals and hand them over to us, 
we could run Bare and do the relevant conversions into `RType` ?
