### ISSUE TITLE
Refined data types do not permit fields with underscore prefixes or strictness annotations

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#531]
Take this data type definition for example:

```haskell
{-@
data Foo = Foo { getFoo :: Int }
@-}
data Foo = Foo { getFoo :: Int }
```

The above code will type-check, but if I add an underscore before the field name:

```haskell
{-@
data Foo = Foo { _getFoo :: Int }
@-}
data Foo = Foo { _getFoo :: Int }
```

... or a strictness annotation to the field:

```haskell
{-@
data Foo = Foo { getFoo :: !Int }
@-}
data Foo = Foo { getFoo :: !Int }
```

... then `liquid` will fail with the same parsing error message in both cases:

```
**** ERROR:  *******************************************************************


 point.hs:2:10: Error: Cannot parse specification:
     unexpected "="
     expecting white space, "[" or "@-}"
```

The workaround is pretty easy: don't use strictness annotations in the refined datatype definition and don't use field names with underscore prefixes.

**Comment by gridaphobe** [comment]
Hrm, the leading underscore is definitely a bug, those are becoming increasingly common as `lens` becomes more popular.

I'm less sure about the strictness annotation. We could parse it and ignore it (since GHC handles strictness concerns), but that might lead users to believe that the strictness annotation in the refined data declaration will affect LH. On the other hand, refusing to parse it means more work for the user when copying/writing the refined data declaration. @Gabriel439 do you have a preference?

Btw, @ranjitjhala this is an excellent example of how our parser could still be improved; the error message/location is extremely misleading, it should say `unexpected "!"`.

**Comment by Gabriel439** [comment]
I don't have strong opinions on the strictness annotation and I'm actually fine omitting them from the refined datatype.

However, underscore prefixes have significance beyond just the `lens` library.  If you define fields without an underscore prefix, but you don't export them:

```haskell
module Example (
    Foo
    ) where

data Foo = Foo { getFoo :: Int }
```

... then `ghc` will warn about the unused field names if you don't use the field names internally within the module (i.e. you always build or pattern match on a constructor positionally) and enable all warnings like with `-Wall`:

```
unused.hs:5:18: Warning: Defined but not used: ‘getFoo’
```

This was the main reason that I added an underscore prefix to the field names, not because of `lens`.

**Comment by nikivazou** [comment]
Yes, we should definitely fix the parser to allow `_` before field names!
