### ISSUE TITLE
mod 2 / multiplication by 2

### ISSUE THREAD

**Issue by gibiansky** [ucsd-progsys/liquidhaskell#563]
I'm not sure what I can do to make Liquid Haskell understand the following code and say it is safe:

```haskell
{-@ type Even = {v:Int | v mod 2 = 0} @-}

{-@ notEven :: Int -> Even @-}
notEven :: Int -> Int
notEven x = x * 2
```

Since `x * 2` is even, `x * 2 mod 2 == 0`, and so this should compile fine.

Where is `mod` defined? Can it be modified somehow to be able to make this work? How can this be worked around?

**Comment by gibiansky** [comment]
The error message is:
```
resources/custom/liquidhaskell/sandbox/1452147805_374.hs:10:13-26: Error: Liquid Type Mismatch
  Inferred type
    VV : {VV : Int | (x == 0 || ?a == 0 => VV == 0) && (x > 0 && ?a > 0 => VV >= x && VV >= ?a) && (x > 1 && ?a > 1 => VV > x && VV > ?a)}
 
  not a subtype of Required type
    VV : {VV : Int | VV mod 2 == 0}
 
  In Context
    VV := {VV : Int | (x == 0 || ?a == 0 => VV == 0) && (x > 0 && ?a > 0 => VV >= x && VV >= ?a) && (x > 1 && ?a > 1 => VV > x && VV > ?a)}

    x := Int

    ?a := {?a : Int | ?a == 2}
```

**Comment by gridaphobe** [comment]
`mod` is built-in, it's an operator the SMT solver understands.

But the problem is not with `mod`, rather with the type we give to `*`. Integer multiplication is undecidable, so we can't model it precisely in the logic. Instead we abstract it with a few properties that cover commonly interesting cases like multiplication by 0. These cases are exactly what LH displays in the inferred type.

Now, you could argue (rightly) that this particular case shouldn't be a problem because you're multiplying by a constant, which is the same as `x + x`. Unfortunately there's a rather annoying technical reason that prevents us from handling multiplication by a constant (it has to do with a transformation we perform on the code before verification).

So for the time being this is a known limitation of LiquidHaskell. You can work around it by rewriting the multiplication to an addition (annoying and inefficient for larger constants), or you can try the `--real` flag which gives `*` a precise type but makes verification undecidable.

**Comment by ranjitjhala** [comment]
Hi @gibiansky,

Add a `{-@ LIQUID "--real" @-}` to the top of your file. e.g.

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1452148662_379.hs

This treats multiplication as proper multiplication.

(@nikivazou, @gridaphobe : We ought to make this default ... ?)

**Comment by gibiansky** [comment]
Cool, thanks!

**Comment by nikivazou** [comment]
@ranjitjhala yes lets make interpreted multiplication and division the default!
