### ISSUE TITLE
Refinements lost when refined functions moved to another module

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#576]
This module type-checks successfully:

```haskell
module Test1 where

import Control.Monad.ST (ST)

import qualified Data.Vector
import qualified Data.Vector.Mutable

{-@
example :: ST s ({ o : Data.Vector.Vector Int | vlen o = 0 })
@-}
example :: ST s (Data.Vector.Vector Int)
example = do
    l0sMutable <- newST 0
    freezeST l0sMutable

{-@ measure mlen :: Data.Vector.Mutable.MVector s a -> Int @-}

{-@
assume newST
    :: n : Int -> ST s ({ v : Data.Vector.Mutable.MVector s a | mlen v == n })
@-}
newST :: Int -> ST s (Data.Vector.Mutable.MVector s a)
newST = Data.Vector.Mutable.new
{-# INLINE newST #-}

{-@
assume freezeST
    :: mv : Data.Vector.Mutable.MVector s a
    -> ST s ({ v : Data.Vector.Vector a | vlen v == mlen mv })
@-}
freezeST :: Data.Vector.Mutable.MVector s a -> ST s (Data.Vector.Vector a)
freezeST = Data.Vector.freeze
{-# INLINE freezeST #-}
```

... but if I move everything except `example` to another module named `Test2`:

```haskell
module Test2 where

import Control.Monad.ST (ST)

import qualified Data.Vector
import qualified Data.Vector.Mutable

{-@ measure mlen :: Data.Vector.Mutable.MVector s a -> Int @-}

{-@
assume newST
    :: n : Int -> ST s ({ v : Data.Vector.Mutable.MVector s a | mlen v == n })
@-}
newST :: Int -> ST s (Data.Vector.Mutable.MVector s a)
newST = Data.Vector.Mutable.new
{-# INLINE newST #-}

{-@
assume freezeST
    :: mv : Data.Vector.Mutable.MVector s a
    -> ST s ({ v : Data.Vector.Vector a | vlen v == mlen mv })
@-}
freezeST :: Data.Vector.Mutable.MVector s a -> ST s (Data.Vector.Vector a)
freezeST = Data.Vector.freeze
{-# INLINE freezeST #-}
```

... and then change module `Test1` to import them:

```haskell
module Test1 where

import Control.Monad.ST (ST)
import Test2

import qualified Data.Vector
import qualified Data.Vector.Mutable

{-@
example :: ST s ({ o : Data.Vector.Vector Int | vlen o = 0 })
@-}
example :: ST s (Data.Vector.Vector Int)
example = do
    l0sMutable <- newST 0
    freezeST l0sMutable
```

... then type-checking module `Test1` fails with the following error:

```
 Test1.hs:(13,1)-(15,23): Error: Liquid Type Mismatch
   Inferred type
     VV : {VV : (Vector Int) | 0 <= vlen VV}
  
   not a subtype of Required type
     VV : {VV : (Vector Int) | vlen VV == 0}
  
   In Context
     VV : {VV : (Vector Int) | 0 <= vlen VV}
```

Note that if I reduce `example` to just `newST` or just `freezeST` then the problem disappears, so this issue has something to do with their interaction.

**Comment by gridaphobe** [comment]
This is an unfortunate combination of LH's inference mechanism and the desugaring of do-notation.

As you know, your `example` desguars into a call to `>>=`

```
example = newST 0 >>= \l0SMutable -> freezeST l0SMutable
```

LH see this and needs to infer a type for `\l0SMutable -> freezeST l0SMutable`, in particular for `l0SMutable`, so it creates a refinement variable `k` to stand for any refinements `l0SMutable` will have. At this point we know `l0SMutable :: {v:MVector s Int | k}`, and we need to solve for `k`. We solve for `k` by instantiating it with a conjunction of a bunch of predicate fragments and then prune away the ones we can't prove until we reach a fixpoint.

Where do the fragments come from? There are a few simple ones "built-in" like equality and ordering, but mostly we mine them from the user's specifications. For example, `example`s type has a fragment `vlen o = 0`, so we extract that and try to prove it for all program variables of type `Vector a`.

The problem is that, for efficiency reasons, we only mine the fragments from the module we're currently checking. Going back to the desugaring of `example`, the type we need to infer for `l0SMutable` is

```
l0SMutable :: {v:MVector s Int | mlen v = 0}
```

but there's the fragment `mlen v = 0` only appears in `Test2`, so we don't try it!

As a solution, you can explicitly provide these fragments using the `qualif` annotation, something like

```
{-@ qualif MLen0(v:MVector s a): mlen v = 0 @-}
```

LH *will* import these fragments from upstream modules, so you can specify a small library of useful fragments (we call them qualifiers for reasons beyond me) somewhere deep in your module hierarchy.

**Comment by ranjitjhala** [comment]
By default we don't generate fragments from *imported* functions
But perhaps, as this example illustrates, that's a bad default! 

(It should be straightforward to fix -- as we *used to* generate them from all signatures.)

@gridaphobe : can you add an option for this? (The relevant code is in Qualifiers ) if you can't get to it soon I can do it next week...

**Comment by gridaphobe** [comment]
@ranjitjhala yes, it's an easy thing to change, but I recall there being a substantial performance hit from it. I experimented with mining fragments from imported types a while ago, and we ended up a bunch of extra, extremely generic qualifiers that I suspect were the source of the slowdown. I'll take another look at it.

**Comment by ranjitjhala** [comment]
There were some pathologies in text with its crazy signatures... But perhaps we could expose some knobs to help find a better default?

**Comment by Gabriel439** [comment]
I'm fine with the `qualif` approach.  However, trying out every possible qualifier in scope seems like a very inefficient approach.  If there's a harder but more efficient way to solve this then I'd prefer to wait for that than add another knob to tweak since I already have a workaround.

**Comment by ranjitjhala** [comment]
Sounds good! Just to make sure I follow, were you referring to the
'qualify' approach as the workaround, or something else? (Btw, the knob is
more for us
to experiment with, to make it easy to search the space for better
defaults, definitely not something that should be exposed to the user IMO.)

**Comment by Gabriel439** [comment]
Yeah, the `qualif` approach is the workaround I was referring to
