### ISSUE TITLE
recommended ways of integrating LH into cabalized builds or testing?

### ISSUE THREAD

**Issue by cartazio** [ucsd-progsys/liquidhaskell#588]
are there any recommended ways of doing so? or is that unexplored territory?

**Comment by gridaphobe** [comment]
We don't have any integration with Cabal at the moment, though that is something we want to work on.

The easiest thing to do currently in terms of running LH as part of the build process would probably be to run it as part of the testsuite. I think most of the test frameworks support running arbitrary programs and checking the exit code or stdout, so you would add tests that run `liquid My/Module.hs` and check that the exit code is 0. (This is how we test LH ourselves https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/test.hs)

More long-term, we want to get closer integration with GHC, perhaps as a plugin, so that you can run LH as part of the normal `cabal build`, but we're not there yet.

Hope that helps!

**Comment by Gabriel439** [comment]
The way I've been doing this is to run `stack exec liquid <file>` from the root of the source tree.  That at least makes sure to pick up the correct dependencies for my current project, but you'll have to wrap that in a test suite like @gridaphobe suggested if you want to make this part of your build process

**Comment by cartazio** [comment]
ok, yeah, the test suite integration is what i want :)

**Comment by cartazio** [comment]
OR; is there a way to do some crazy (ab)use of the program file preprocessor stuff and do it that way?

**Comment by spinda** [comment]
[liquidhaskell-cabal](https://github.com/spinda/liquidhaskell-cabal) is now the recommended way to integrate LH with a Cabal or Stack-based build. Please let me know if it doesn't meet your needs!
