### ISSUE TITLE
Ignore commented out annotations

### ISSUE THREAD

**Issue by rpglover64** [ucsd-progsys/liquidhaskell#617]
```
-- {-@ foo :: () @-}
-- foo = ()
```
and
```
{-
{-@ foo :: () @-}
foo = ()
-}
```

Both cause LH to complain about `foo` being undefined.

**Comment by ranjitjhala** [comment]
Thanks! This has bothered me too! 
@spinda do you think you can take a quick look as you are working with the parser?

**Comment by spinda** [comment]
The code that grabs the `{-@ @-}` comments is [here](https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/Parse.hs#L925-L939). It just skips everything until it hits a `{-@`. To skip commented-out annotations, it could:

1. Skip everything until `{-`
2. If the next character is `@`, parse a specification. Otherwise, skip the entire comment.
3. Repeat.

**Comment by ranjitjhala** [comment]
​That sounds right...​

**Comment by rpglover64** [comment]
What about inline comments?

**Comment by spinda** [comment]
Ah, true. Also it should deal with things that look like comments within quotes. So:

1. Skip everything until `"`, `--`, or `{-`.
2. If `"`, skip a Haskell string. Go to 1.
3. If `--`, skip the rest of the line comment. Go to 1.
4. If `{-` and the next character is `@`, parse a specification. Otherwise, skip the entire comment. Go to 1.

**Comment by rpglover64** [comment]
GHC-the-library is already a dependency, right? Does it not expose a parser that preserves comments? (I feel like that would be less maintenance burden; other than that, this description looks good to me)

I think quasiquotes are rare enough that they're not a worry here.

**Comment by spinda** [comment]
GHC's parser is implemented in a great big Happy file and very monolithic. I don't think we'd be able to reuse parts of it here.

However, now that you mention it, there *is* the [ApiAnnotations](https://ghc.haskell.org/trac/ghc/wiki/ApiAnnotations) interface, which is designed for extracting special comments like Haddock's from Haskell source. But it doesn't retain the location of each comment, so we'd have to somehow obtain that manually (searching through the source for the comment text...?).

**Comment by alanz** [comment]
The API Annotations interface does provide locations for the comments.

**Comment by alanz** [comment]
And if you set `Opt_KeepRawTokenStream` in the dynflags you can access the comments as a field in `ParsedModule` when invoking GHC.

**Comment by spinda** [comment]
It associates certain comments with `SrcSpan`s, but those `SrcSpan`s correspond to the location of a nearby syntax element rather than the location of the comment itself, and top-level comments don't have real `SrcSpan`s attached at all. There's an example of the output on the wiki page. Is there other location info that can be extracted through ApiAnnotations?

`ParsedModule` has `pm_annotations`, the ApiAnnotations stuff, and `pm_parsed_source`, the parsed AST which I don't believe retains any comment information.

**Comment by alanz** [comment]
The `ApiAnns` type is defined as

```haskell
type ApiAnns = (Map ApiAnnKey [SrcSpan], Map SrcSpan [Located AnnotationComment]) 
```
For the comments, the map is indexed by the nearest enclosing `SrcSpan`, but the `AnnotationComment` has its original location in the source file. 

So `Map.elems (snd anns)` will give you a list of located comments.

**Comment by spinda** [comment]
Ah ha, I should have looked at that closer. Thanks!

Then ApiAnnotations should be perfect for our use case.

**Comment by ranjitjhala** [comment]
Thanks a bunch @alanz !!!

**Comment by gridaphobe** [comment]
So is the idea now that instead of parsing the module ourselves and extracting the comments, we just extract these `AnnotationComment`s from GHC itself and discard the ones that don't start with `{-@`?

**Comment by spinda** [comment]
Exactly. Does that sound good?

**Comment by gridaphobe** [comment]
Sounds great!

**Comment by ranjitjhala** [comment]
+1

**Comment by spinda** [comment]
The `api-annotations` branch is pushed and will hopefully be merged soon.
