### ISSUE TITLE
Weirdness in splitAt

### ISSUE THREAD

**Issue by sorawee** [ucsd-progsys/liquidhaskell#658]
If I have `test1` and `test2`, LH can check that this is safe, so this is good.

```
{-@ test1 :: n: {v : Int | v >= 0} -> lst: {v : [a] | n < len v} -> {v : [a] | len v = len lst - n } @-}
test1 :: Int -> [a] -> [a]
test1 n lst = b where (_, b) = splitAt n lst


{-@ test2 :: n: {v : Int | v >= 0} -> lst: {v : [a] | n < len v} -> {v : [a] | len v = n } @-}
test2 :: Int -> [a] -> [a]
test2 n lst = a where (a, _) = splitAt n lst
```

Weirdly, if I have `test3` alone, it's unsafe

```
{-@ test3 :: n: {v : Int | v >= 0} -> lst: {v : [a] | n < len v} -> {v : [a] | len v = len lst } @-}
test3 :: Int -> [a] -> [a]
test3 n lst = a ++ b where (a, b) = splitAt n lst
```

Now, if I put `test1`, `test2`, `test3` together, it's safe again... although `test1`, `test2`, `test3` has no relation to each other at all...

```
{-@ test1 :: n: {v : Int | v >= 0} -> lst: {v : [a] | n < len v} -> {v : [a] | len v = len lst - n } @-}
test1 :: Int -> [a] -> [a]
test1 n lst = b where (_, b) = splitAt n lst


{-@ test2 :: n: {v : Int | v >= 0} -> lst: {v : [a] | n < len v} -> {v : [a] | len v = n } @-}
test2 :: Int -> [a] -> [a]
test2 n lst = a where (a, _) = splitAt n lst

{-@ test3 :: n: {v : Int | v >= 0} -> lst: {v : [a] | n < len v} -> {v : [a] | len v = len lst } @-}
test3 :: Int -> [a] -> [a]
test3 n lst = a ++ b where (a, b) = splitAt n lst
```

I see the annotation for `splitAt` and am a little bit confused:

```
splitAt :: n:_ -> x:[a] -> ({v:[a] | (if (n >= 0) then (Min (len v) (len x) n) else ((len v) = 0))},[a])<{\x1 x2 -> (len x2) = (len x) - (len x1)}>
```

But I tried:

```
Prelude> splitAt -1 [1, 2, 3, 4]

<interactive>:2:1:
    Non type-variable argument
      in the constraint: Num (Int -> [a] -> ([a], [a]))
    (Use FlexibleContexts to permit this)
    When checking that ‘it’ has the inferred type
      it :: forall a t.
            (Num t, Num (Int -> [a] -> ([a], [a])),
             Num ([t] -> Int -> [a] -> ([a], [a]))) =>
            Int -> [a] -> ([a], [a])
```

so it seems that there should be a constraint on `n` that it's nonnegative, and then we can drop the `if` expression, yes?

**Comment by ranjitjhala** [comment]
@sorawee this has to do with our defaults for generating qualifiers. 

Whats happening is this:

To prove `test3` I think you need the qualifiers (think "refinement fragments") that appear in the output type of `splitAt`, namely `len v = len _ - _` where the `_` can be instantiated with variables in scope. (The reason you need this is to give a proper type to the tuple `(a, b)` in `test3`. Now, 

1. when you have `test1 _in_ the module being checked, then the qualifier is "obtained" from its signature, but,
2. when you don't have `test1` it cannot be obtained _from the code in the current module_.

Now, it is possible to _also_ obtain it from the signature of `splitAt`, but we don't do that _by default_,
as it usually pulls in too much stuff (and is a speed hit sometimes.) However, you can switch it on with `--scrape-used-imports` (which doesn't affect things here) and then you will find that the `test3` alone _also_ returns SAFE.

This issue is currently being researched -- but as of now this is where we are :-/ -- does this make sense?

BTW, You are right, we could put the `n >= 0` precondition and drop the `else` part, but thats not whats happening here...

**Comment by ranjitjhala** [comment]
As an aside, this is a great question -- @gridaphobe or @nikivazou can you think of some way we can "curate" these and add them to a README or FAQ or PITFALLS.md or such?

**Comment by ranjitjhala** [comment]
@sorawee ps: the bizarre GHC error you're seeing is because its parsing it as  `(splitAt - 1) ...` if you instead use parens, you get: 

```
Prelude> splitAt (-1) [1, 2, 3, 4]
([],[1,2,3,4])
```

**Comment by sorawee** [comment]
Ah, that's why! Thanks for the explanation :)
