### ISSUE TITLE
Random constraint generation error

### ISSUE THREAD

**Issue by themattchan** [ucsd-progsys/liquidhaskell#734]
I get a failure with the following `Category` instance, when we hit the `id` component (with type `Accum a a`).

```haskell
{-# LANGUAGE GADTs #-}
import Control.Category
import Prelude hiding ((.), id)

data Accum a b where
  Accum :: (s -> a -> (s, b)) -> s -> Accum a b

-- | We can pass the outputs of one 'Accum' as the inputs of the next.
instance Category Accum where
  id = Accum (,) ()
  Accum step2 initialState2 . Accum step1 initialState1 = Accum step (initialState1, initialState2)
    where
      step (s1, s2) a = let (s1', b) = step1 s1 a
                            (s2', c) = step2 s2 b
                        in ((s1', s2'), c)

```

```
$ liquid AccumError.hs
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.


**** DONE:  Parsed All Specifications ******************************************


**** DONE:  Loaded Targets *****************************************************


**** DONE:  Extracted Core using GHC *******************************************


**** DONE:  annotate ***********************************************************


**** RESULT: ERROR *************************************************************


 <no location info>: Error: Uh oh.
     addC: malformed constraint:
{lq_tmp$x##580 : (Accum {VV##502 : a^"lq_tmp$x##504" | $k_##503[VV##508:=lq_tmp$x##580]} {VV##505 : a^"lq_tmp$x##507" | $k_##506[VV##508:=lq_tmp$x##580]})^"lq_tmp$x##510" | $k_##509[VV##508:=lq_tmp$x##580]}
 <:
(Accum a a)
```

However this should be fine because the definition of  `Category` is

```haskell
class Category cat where
id :: cat a a 
(.) :: cat b c -> cat a b -> cat a c
```

Thoughts?

[AccumError.txt](https://github.com/ucsd-progsys/liquidhaskell/files/314924/AccumError.txt)

**Comment by ranjitjhala** [comment]
@nikivazou is this some weird "strata" related thing? The types seem the same if you set aside the strata...

**Comment by nikivazou** [comment]
Into it. It should be that the type variables are different (even though are printed the same).

**Comment by nikivazou** [comment]
The bug has to do with Haskell type being different [here](https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/Constraint/Monad.hs#L67) because one of them is abstracted over `(a :: *)` and the other over `(a :: k)` (different kinds). 

I am removing the above check, as we already check type equivalence of constraints [here](https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/Constraint/Split.hs#L211).

But to properly fix this we should reason about kind application. Any help from experts would be appreciated @simonpj @goldfirere: What are the semantics of kind application, since there is no kind abstraction? For example:

In the dictionary construction 
```
 Main.$fCategory*Accum [InlPrag=[ALWAYS] CONLIKE]
   :: Control.Category.Category Main.Accum
 [LclIdX[DFunId],
  Str=DmdType,
  Unf=DFun: \ ->
        Control.Category.D:Category TYPE * TYPE Main.Accum $cid $c.]
 Main.$fCategory*Accum =
   (Control.Category.D:Category @ * @ Main.Accum $cid) $c
``` 

 We have 
```
Control.Category.D:Category  
  :: (forall (a :: k). cat a a)
  -> (forall (b :: k) (c :: k) (a :: k). cat b c -> cat a b -> cat a c)
  -> Control.Category.Category
```

How do I know that in `Control.Category.D:Category @ *` I need to substitute THE `k` as `k := *`. 

Now LiquidHaskell [ignores the kind application](https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/Constraint/Generate.hs#L1007) and infers
```
Control.Category.D:Category @ * @ Main.Accum
   :: (forall (a :: k). Main.Accum a a)
   -> (forall (b :: k) (c :: k) (a :: k).Main.Accum b c -> Main.Accum a b -> Main.Accum a c)
   -> Control.Category.Category
```

which leads to a "kind error" since
```
$cid :: forall (a :: *). Main.Accum a a
```

**Comment by nikivazou** [comment]
Fixed, so temporally closing until we find a proper way to apply kinds.

**Comment by goldfirere** [comment]
I think GHC is unhelpfully suppressing some output. Have you tried with `-fprint-explicit-kinds -fprint-explicit-foralls`? That might show you what you need.

**Comment by nikivazou** [comment]
Thanks @goldfirere but my problem is not in the printing, but in the CoreSyn representation. There is no kind abstraction in the representation. _For example_, the type `forall (a:k). a` is represented with one Pi for the type variable. I would expect another Pi for the kind too.

**Comment by goldfirere** [comment]
Then something is very funny. If you just had `forall (a:k). a`, without a binding for `k`, then you'd have an error with `-dcore-lint`. (Actually, that's an error even with the `forall k`, because the body of a `forall` must be `TYPE r` for some `r`.) Try `-fprint-explicit-runtime-reps`. If that's the flag that does it, then we have a bug in the implementation of the flag.

Alternatively, you say it's not the printer, but in the CoreSyn. How have you determined this? Or perhaps there is some LH-specific processing that removes the kind binders? The core should certainly have the kind binders.

**Comment by nikivazou** [comment]
There should be a liquid Haskell possessing that removes the kinds! Sounds
like a hack I implemented when we didn't deal with code with kinds. Thanks
Richard!
