### ISSUE TITLE
Support imported `axiomatized` functions

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#776]
in short, make the following test work.

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/todo/ReflImp.hs

Note that the "flattened" version

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/todo/Refl.hs

works. The `axiomatize` stuff is pretty useless until we fix this.

**Comment by nikivazou** [comment]
@spinda was looking into that. It is tricky though, since the `ReflImp` does not have access to the code for incr. 
One solution is to get access of `incr` code, the cleaner one is to create these `.lhi` intermediate files at which `incr` exposes its reflected type. 

The same applies for lifted Haskell measures.

**Comment by ranjitjhala** [comment]
Why do we need the code? Why can't we just save the type in an Lhi file?

**Comment by ranjitjhala** [comment]
This was addressed a long time ago, right?

**Comment by nikivazou** [comment]
I hope so :)
