### ISSUE TITLE
Documentation on how to make abstract refined data types

### ISSUE THREAD

**Issue by mckeankylej** [ucsd-progsys/liquidhaskell#797]
I am trying to make an abstractly refined list seen here:
```haskell
data List a
   = Nil
   | Cons { hd :: a, tl :: List a }

{-@ data List a <p :: a -> a -> Prop>
       = Nil
       | Cons {hd :: a, tl :: List (a<p hd>) @-}

{-@ test :: (List Int)<{\x y -> x < y}> @-}
test :: List Int
test = Cons 5 (Cons 4 Nil)
```
The problem is this code liquid type checks when it shouldn't (what a weird world we live in where 5 < 4).

On top of this your blog post "putting things in order" has liquid haskell code that your parser cant read such as:
```haskell
data (a,b)<p :: a -> b -> Prop> = (x:a, b<p x>) 
```
and 
```haskell
data [a] <p :: a -> a -> Prop> where
   | []  :: [a] <p>
   | (:) :: h:a -> [a<p h>]<p> -> [a]<p>
```
I don't know how to define refined data types that take abstract refinements like above without the GADT like syntax.

**Comment by ranjitjhala** [comment]
Hi @mckeankylej,

Sorry about that, I keep deferring writing documentation/tutorials on abstract refinements because we want to re-implement them in a cleaner fashion (c.f. #581). 

This is probably the best example of the abstract refinement syntax:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/pos/Map.hs

In your particular example, you want something like:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1469603840_14511.hs

Whats happening here is that you want to write:

```
{-@ test :: (List<{\x y -> x < y}> Int) @-}
```

i.e. push the application to the `List` constructor, instead of outside. Outside is the only option for the `[...]` style lists but its very confusing as you've unfortunately discovered 
(which is why we want to redo the syntax and implementation.)

@nikivazou we _should_ be reporting malformed specification here, instead of silently dropping the abstract refinement (c.f. #82)

Thanks for pointing this out, I will update the README!
