### ISSUE TITLE
How can liquid haskell turn Vector.! into unsafeIndex?

### ISSUE THREAD

**Issue by rrnewton** [ucsd-progsys/liquidhaskell#817]
This was a question that came up in our meeting today.

Typed Racket, for example, is an optional type system that can actually affect program performance by substituting specialized versions of functions.  Liquid Haskell, as I understand, is different -- it's a "linter" whose output is a boolean (pass or fail) rather than a new, preprocessed program.

We're embarking on a struggle to make more of Stackage SafeHaskell.  In the process, the vector package provides one tricky case, which becomes more tricky if we're aiming for an integrated Safe/Liquid Haskell story:
- `Data.Vector.unsafeIndex` -- if we want this module to be Safe, we need to either remove this export or deprecate it and force a bounds check.
- `Data.Vector.Unsafe.unsafeIndex` -- this (future) module can export the naughty, bound-check free version.

We can use `.spec` files, like the existing `Vector.spec` in the repo, to add liquid types to either or both of these imports.  However, even if we import `Unsafe.unsafeIndex` and prove it safe, we cannot undo the fact that GHC now concludes the program is unsafe.  The only compromise we thought of in our meeting today was this:
- Add a new module, e.g. `Liquid.Data.Vector`.  It claims "Safe" and also exports _only_ unsafe versions of indexing, together with their refinements.

But, the existence of this module is a blight on the normal SafeHaskell ecosystem.  (If you use it _without_ using liquid Haskell, you break SafeHaskell.)  Thus whatever package contains the wrapper should never be trusted by a safe haskell installation.  It should be blacklisted.

Wrapping and reexporting is clumsy.  But isn't this an issue that comes up whenever we want an  application with mixed partial-verification -- some vector accesses in the application may be proven in bounds, but other vector accesses may not be.  How to accommodate both?

**Comment by gridaphobe** [comment]
I think the answer lies in closer integration between LiquidHaskell and GHC. We have an item in our backlog of engineering work to re-imagine LH as a GHC Core-to-Core plugin, primarily because it would relieve us of a lot of fidgeting in terms of setting the right package versions, language extensions, etc. But it could also open the door to using LH results to optimize the Core in ways GHC can't, or as you suggest, by substituting *unsafe* versions of functions with *safe* versions that do a runtime check, when LH can't discharge the pre-condition statically.

There's a fair bit of engineering involved here, both on the LH side *and* on the GHC side.

**Comment by ranjitjhala** [comment]
Yes, I think so far by design we've aimed at not
changing the dynamic behavior of code at all.

Even with the closer integration, it seems tricky.

As I understand it, you need almost a "gradual"/"soft"
refinement type system, in that a call:


```
  a ! i
```

is treated as / rewritten to

```
unsafeIndex a i
```

ONLY if LH is used and able to verify the access as safe?

Seems possible in theory but will definitely need
some GHC hacking expertise. Seems like we need to
know (writing down for my sake):

1. For each "unsafe" function, the corresponding
   "safe" variant,

2. Use the core-to-core plugin to replace the
   unsafe function with its safe variant IF the
   LH check fails.

(alternately)

2'. By default use the SAFE variant in the code,
    and replace with UNSAFE variant ONLY IF the LH CHECK passes.

This way (2') by default -- if you are not using LH -- then you
must use the SAFE variant.

**Comment by rrnewton** [comment]
I like (2').  Maybe this is a scenario to one day have LH-guarded rewrite rules.  Where a simple one would just be `(!) = unsafeIndex`.

**Comment by ranjitjhala** [comment]
Thats an cool idea!!
