### ISSUE TITLE
Infix operators in type signatures

### ISSUE THREAD

**Issue by vikraman** [ucsd-progsys/liquidhaskell#819]
While it is possible to axiomatize an infix function, using it in a type signature results in a parse error.

``` haskell
{-@ axiomatize .+. @-}
(.+.) :: N -> N -> N
Zero .+. n = n
(Suc m) .+. n = Suc (m .+. n)

{-@ lemma :: { v:() | Zero .+. Zero == Zero } @-}
lemma :: ()
lemma = Zero .+. Zero ==. Zero *** QED
```

```
    84  28 error           Error: Cannot parse specification:

 84 | {-@ lemma :: { v:() | Zero .+. Zero == Zero } @-}
                                 ^

     unexpected "."
     expecting operator, "==", "=", "~~", "!=", "/=", "!~", "<", "<=", ">", ">=" or "(" (haskell-liquid)

```

**Comment by nikivazou** [comment]
Parsing with infix operators is tricky and we currently do not support it. 

I acknowledge that this issue is annoying, but currently now high in my TODO list, sorry. 
@spinda was willing to fix it, but @vikraman if you are willing to give it a try here is the refinement parser 

https://github.com/ucsd-progsys/liquid-fixpoint/blob/develop/src/Language/Fixpoint/Parse.hs#L276

**Comment by vikraman** [comment]
Ouch, this also causes tuples to not work.

**Comment by nikivazou** [comment]
Yeap, in logic we only support prefix functions. 

Lists, tuples, or anything infix is not properly parsed into logic.

**Comment by ranjitjhala** [comment]
Also: #819, #843, #902 

@nikivazou this is a really annoying limitation, because you cannot
even  reflect any operator. For example in the below, LH _never_ has 
to actually parse an infix operator, so it _should_ be easy to replace `mappend`
with `++` and yet we cannot (I get some weird error.) At the very least stuff like 
the below where the LH parser doesn't change should be easy to fix?

```haskell
data List a = Emp | a ::: List a  deriving (Eq)

{-@ reflect append @-}
append Emp        ys = ys
append (x ::: xs) ys = x ::: (xs `append` ys)

{-@ inline assocThm @-}
assocThm xs ys zs
  = (xs `append` ys) `append` zs == xs `append` (ys `append` zs)

{-@ assocPf :: xs:_ -> ys:_ -> zs:_ -> { assocThm xs ys zs } @-}
assocPf Emp ys zs
  =   (Emp `append` ys) `append` zs
  ==. Emp `append` (ys `append` zs)
  *** QED

assocPf (x ::: xs) ys zs
  =    ((x ::: xs) `append` ys)  `append` zs
  ==.   (x ::: (xs `append` ys)) `append` zs
  ==.    x ::: (xs `append` (ys  `append` zs)) ? assocPf xs ys zs
  ==.   (x ::: xs) `append` (ys  `append` zs)
  *** QED
```

**Comment by nikivazou** [comment]
@ranjitjhala you can reflect ++ see https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/T819A.hs

**Comment by nikivazou** [comment]
I suspect you get a weird error of the form `Unbound Symbol is_Emp`  because you are trying to reflect an operator on Lists in the logic, but you have not reflected the List data type. Reflection of the list data type happens if you 

 1. refine the list data types {-@ data List ....@-}
 2. use the `exactdc` flag

I ack that the type error is non usefull....

**Comment by ranjitjhala** [comment]
Thanks!

No the error I got was specifically about infix operators, will try again
to see what the matter was...

**Comment by ranjitjhala** [comment]
Oops, my error was

/Users/rjhala/research/stack/liquidhaskell/benchmarks/pldi17/pos/AppendList.hs:21:13:
Error: Cannot promote Haskell function (++) to logic

turns out I was writing

   {-@ reflect (++) @-}

instead of

   {-@ reflect ++ @-}

**Comment by ranjitjhala** [comment]
looks like this was fixed awhile back. thanks @nikivazou !
