### ISSUE TITLE
this should never happen

### ISSUE THREAD

**Issue by Icelandjack** [ucsd-progsys/liquidhaskell#857]
```haskell
{-@ impossible :: {4 = 5} -> Int @-}
impossible msg = 4
```

tells me to report

```
$ liquid --totality tcXK.hs
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************
 
liquid: <no location info>: Error: Uh oh.
    This should never happen! If you are seeing this message, 
please submit a bug report at 
https://github.com/ucsd-progsys/liquidhaskell/issues 
with this message and the source file that caused this error.

RefType.toType cannot handle: {VV : _ | 4 == 5}
```

**Comment by ranjitjhala** [comment]
Thanks for pointing this out @Icelandjack ! 

@nikivazou and @gridaphobe : As in #858 the issue here is with handling holes when the refined and Haskell types don't match.

The "fix" right now is to either
 
1. Provide a haskell type, so any of the following works:

```
impossible :: a -> Int
```

2. Not use the `{p}` syntax but write the full type `{v:t | p}` OR 

```
{-@ impossible :: {a | 4 == 5} -> Int @-}
```

which then gives a nicer error:

```
 /Users/rjhala/research/stack/liquidhaskell/tests/todo/T857.hs:2:19-37: Error: Specified Type Does Not Refine Haskell Type for Main.impossible
 
 2 | {-@ impossible :: {a | 4 = 5} -> Int @-}
                       ^^^^^^^^^^^^^^^^^^^

 The Liquid type
  
     forall a. a -> GHC.Types.Int
  
 is inconsistent with the Haskell type

     forall t a. GHC.Num.Num a => t -> a
```

**Comment by ranjitjhala** [comment]
But really the issue is that the hole resolution should gracefully fail when it can't match the haskell type. At the _very_ least, instead of the gross "cannot handle toType", we should just 

1. Traverse each resolved signature to check there are *no holes left*
2. If there are holes left fail with a nice error message:

```
Cannot resolve holes in signature for

   binder :: type 

Could you either

1. Write the Haskell type signature for binder or,
2. Not use holes? 
```



Cannot

**Comment by gridaphobe** [comment]
Strange, I seem to recall having an explicit failure mode in the hole resolution code when the structure of the types doesn't match, e.g. the extra `Num a` constraint in the Haskell type.

**Comment by nikivazou** [comment]
@gridaphobe are you on it, or should I take a look? 

It is a really annoying error....
