### ISSUE TITLE
Proof fails without an unused as-pattern.

### ISSUE THREAD

**Issue by TomMD** [ucsd-progsys/liquidhaskell#969]
I have a proof over tuples which only works when an unnecessary (from a Haskell perspective) as-pattern exists.  In the below please see the as-pattern on `swp_prop`.

```
{-@ LIQUID "--exact-data-cons" @-}
module Lists where

import Language.Haskell.Liquid.ProofCombinators
import Data.Tuple
import Data.List

swp :: (a,b) -> (b,a)
swp (a,b) = (b,a)
{-@ reflect swp @-}

mkPair :: a -> b -> (a,b)
mkPair a b = (a,b)
{-@ reflect mkPair @-}

-- Theorem snd_fst_is_swap : ∀(p : natprod),
-- --   (snd p, fst p) = swap_pair p.
--
-- -- 1. `swap` is out of scope
-- -- 2. Infix syntax, to include tuple construction, is not supported.
{-@ swp_prop :: p:(a,b) -> { fst (mkPair (snd p) (fst p)) == fst (swp p) } @-}
swp_prop :: (a,b) -> ()
swp_prop p@(_,_)
   = swp p
  ==. mkPair (snd p) (fst p)
  *** QED
```

This is valid according to `liquid`.  If you remove rewrite it with `swp_prop p@(_,_) ~~> swp_prop p` it seems things should work - the tuple type is well established - but instead `liquid` yidds:

```
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.
...snip...
**** RESULT: UNSAFE ************************************************************


 /private/tmp/test.hs:(24,6)-(26,9): Error: Liquid Type Mismatch
   Inferred type
     VV : ()

   not a subtype of Required type
     VV : {VV : () | fst (mkPair (snd p) (fst p)) == fst (swp p)}

   In Context
     p : (a, b)
```

**Comment by nikivazou** [comment]
This happens because the functions, `fst` and `snd` that you use in your theorem are measured and Liquid Haskell knows about the definitions of measures via refining the types of the data constructors. 

In your case the refined data constructor is the pair data constructor `(,)`. Thus, to put the definitions of `fst p` and `snd p` in the logic, you need to put use the data constructor `(,)` in Haskell, which happens when you have the cast `p@(_,_)`.

Does this make any sense? 
 
This behavior is expected when you know how measures are implemented, but I understand your confusion. We should address this issue so that Liquid Haskell behaves more predictable, but I do not still know a clean solution to address it.

**Comment by ranjitjhala** [comment]
Its like `destruct` in coq -- except here we know there _is_ a single case, but still we are forcing the programmer to do the `destruct`.
