### ISSUE TITLE
weird proof script

### ISSUE THREAD

**Issue by zilinc** [ucsd-progsys/liquidhaskell#979]
In file https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/strings/pos/DivideAndQunquer.hs#L215, I'm not convinced by the proof, although LH tells me it's safe. But should `append N z ==. z`?

**Comment by ranjitjhala** [comment]
Dear Zilin,

you are right! Thanks for pointing out that error.

The reason LH was accepting the proof is because
neither that line nor the next one are actually
needed, i.e. the proof works even if you _delete_
them (as I have in the fixed version), try it
for yourself. Thus the "intermediate" equalities
are only there to make the proof "readable" (but,
in this case, did not affect the correctness...)

@nikivazou -- that said, we *must* fix the type class
issue  about checking the intermediate `==.` in order
to make the proofs actually usable, otherwise other
careful users like Zilin will be quite perplexed when
proofs succeed or fail!

- Ranjit.
