### ISSUE TITLE
Cannot parse .pred file

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquidhaskell#982]
The file `./liquidhaskell/include/Language/Haskell/Liquid/Prelude.pred` contains the lines

```
assume (.) :: forall b c a. forAll q1:a q2:b q3:c. (b^q2 -> c^q3) -> (a^q1 -> b^q2) -> a^q1 -> c^q3
assume (,) :: forall a b. forAll q1:a q2:b. a^q1 -> b^q2 ->(a^q1, b^q2)
```

Neither of these can be parsed via `singleSpecP`, failing on the initial operator in parens.

Should they be able to be parsed? Is there some other parser entrypoint that should be used? Does this file get used?

**Comment by alanz** [comment]
For background, I am trying to work out what

```haskell
binderP :: Parser Symbol
binderP    =  try $ symbol <$> idP badc
          <|> pwr <$> parens (idP bad)
  where
    idP p  = many1 (satisfy (not . p))
    badc c = (c == ':') || (c == ',') || bad c
    bad c  = isSpace c || c `elem` ("(,)" :: String)
    pwr s  = symbol $ "(" `mappend` s `mappend` ")"
```

is intended to parse.

**Comment by ranjitjhala** [comment]
Hi @alanz,

1. I *think* the `.pred` file is dead code -- i.e. no need to support it. (@nikivazou this seems to be the vestiges of the strata-polymorphism experiment that is currently on hold right?)

2. `binderP` is supposed to parse binders i.e. in  every type annotation is of the form `x :: T` the `x` is the binder. It is a mess because we also needed to support infix style binders (e.g. `(.)` which can be wrapped in parens.

At least, this is my recollection. @nikivazou  do you have anything to add or correct?

Thanks!

Ranjit.

**Comment by nikivazou** [comment]
Seems correct, you can kill parsing of the `Prelude.pred` file.

**Comment by alanz** [comment]
I agree with you on `binderP`, I did some experiments and checked what failed. It has to accept a very diverse set of chars, from operators to things like `GHC.Types.I#`.

**Comment by alanz** [comment]
No action required in parsing.  If the .pred files should be deleted I leave it to someone else. @nikivazou ?
